### ISSUE TITLE
Rich Text Mode: loading note issue

### ISSUE THREAD

**Issue by MiMoHo** [nextcloud/notes#1008] opened 2023-03-29 00:05 UTC
When opening a .txt note in Rich Text Mode, it takes (much) longer to load than in classic editing mode and it is instantly marked as edited by a star in the sidebar although no change was performed. When I refresh the page, it asks me if I want to leave the page as it thinks there are unsaved changes. And indeed the Rich Text Mode messes up my formatting as reported in #1007 . When corrected with editing mode, the note can no longer be loaded in Rich Text Mode. The note stays blank with an endless loading circle. The file type is not changed from .txt. The note can then only be accessed in editing mode.

## Server

- Notes app version: 4.7.2
- Nextcloud version: 26.0.0
- OS: Linux
- Web server: 
- PHP version: 8.1
- Database: MySQL

## Client

- Browser (incl. version): Firefox for Mac 111.0.1
 - OS: macOS 12.6.3

**Comment by Yiannis128** [comment] 2023-03-31 10:30
I'm experiencing this issue as well. The issue can only be overcome by using the MD mode instead.

**Comment by florianwgnr** [comment] 2023-03-31 16:55
Same issue for me, using the new rich text editor just makes no sense at the moment.

**Comment by halivorg** [comment] 2023-04-03 08:52
Same issue for me as well, on two different Nextcloud instances. I heavily use the Notes app and it would be wonderful, if the rich edit module would be fully applicable. Thanks a lot!

**Comment by juliushaertl** [comment] 2023-04-03 08:57
Can you check the browser console for errors? Also can you tell which file extension you have set?

**Comment by halivorg** [comment] 2023-04-03 09:13
Hi Julius, my file extension is set to md. The behaviour is, that in rich mode the save-button doesn't work (red dot stays) and the browser asks for leaving the page due to unsaved content when going to another menu entry. I am using notes 4.7.2 on Nextcloud 26.0.0 with Firefox 111.0.1. The console says:
![grafik](https://user-images.githubusercontent.com/117348369/229465898-9a6d7409-9cc9-4618-81ec-2d75b18b05fe.png)

**Comment by juliushaertl** [comment] 2023-04-06 07:34
Thanks for that. I managed to reproduce this and pushed a fix in https://github.com/nextcloud/text/pull/4028

**Closed** 2023-04-12 15:26 UTC
Labels: bug, need to reproduce

**Comment by ryester19** [comment] 2023-06-15 12:50
This appears to still be a problem for me with NC27. Simply opening up the .md note using the rich text editor causes it to be marked as modified. Leaving Notes causes Librewolf (Firefox) to complain about unsaved changes

Console log: https://gist.github.com/ryester19/7aaa233f43af76a941738bc9acd69422

Nextcloud version: 27.0.0
Notes version:  4.8.0
Text version: 3.8.0

**Comment by iluvatyr** [comment] 2023-12-20 12:21
I probaly lost a good portion of my notes due to this. This should be fixed ASAP
