### ISSUE TITLE
HTTPS connection disconnect with Firefox

### ISSUE THREAD

**Issue by aldakur** [nextcloud/notes#523] opened 2020-05-26 08:36 UTC
HTTPS connection disconnect with Firefox. I have my nextcloud with Let's Encrypt certificate but when I clicked on notes app suddenly connection not secure appear in URL bar on Firefox. Since that moment every thing works wrong. Every thing works without security connection. For example if I return to my calendar or my files.

 Apparently  every thing works good with Chrome.

**Comment by korelstar** [comment] 2020-05-26 19:23
That's very strange. I can't imagine how the notes app could break the HTTPS connection. Can you please give more details?

- When exactly does this happen? Directly after clicking on the notes icon or not until the notes list is loaded / the first note is loaded?
- Which error happens exactly? Please click on the warning (resp. the info icon) in order to open more detailed information. Can you provide some screenshots of this?

**Comment by aldakur** [comment] 2020-05-26 22:08
Hi,

Now I don't have any notes. Only I installed app. The error appear when I clicked on notes app main icon. 

This is the error:
![https](https://user-images.githubusercontent.com/1963922/82955005-30cba600-9fae-11ea-8dae-a57926b49605.png)

**Comment by korelstar** [comment] 2020-05-27 05:44
Thanks for providing the screenshot. This means that some part was loaded using HTTP instead of HTTPS. That should not happen in Nextcloud. Maybe it's a configuration issue.

In order to analyze this further, we have to figure out which part is the problem. Therefore, please open Firefox' Network analysis console by pressing CTRL+SHIFT+E. Please ensure, that the filter is set to "All" (see [docs](https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/toolbar) for help). Then open the note app in the current browser tab. You should see a list of files that are requested by your browser from the server. In the column "Domain", you see a lock icon, if the file was requested securely. Please search for an entry, that doesn't have this lock and provide a screenshot of that entry.

Please have also a look on the Console (CTRL+SHIFT+K). Maybe, there is also a related entry. If you're unsure, please provide a screenshot.

Btw.: which version of Nextcloud and the Notes app do you use? Which version of Firefox? Do you use any add-ons in Firefox?

**Comment by aldakur** [comment] 2020-05-27 15:41
Hi, 

This is the result of network analysis console:
![https-error](https://user-images.githubusercontent.com/1963922/83040930-28bc4680-a040-11ea-9ac7-079f8999adf4.png)

Firefox version is `76.01`. I know that I told you with chrome every thing worked good but I was wrong. With Chrome `81.0.4044.138` I have the same error. Apparently every thing is work good with Brave Browser (`Versión 1.8.96 Chromium: 81.0.4044.138 (Official Build) (64-bits)`).

I installed nextcloud with Docker compose like this: `nextcloud:latest` notes app version is `3.4.0`

Thank You.

**Comment by korelstar** [comment] 2020-05-27 18:54
It looks like all request are done using HTTP instead of the initially used HTTPS. Therefore, I'm pretty sure, that this is not caused by the Notes app. Please have a detailed look at your Nextcloud server configuration. Maybe, the configuration parameter `overwriteprotocol` could be the solution (set it to `https`). But I haven't used the Nextcloud Docker images, so I have no experience with that. I suggest to ask for help in the Nextcloud forum.

**Comment by aldakur** [comment] 2020-05-27 22:12
Yes, I think the problem is not note app because I made the following change in my NextClound condig.php file and now apparently the connection is safe.
```
'overwrite.cli.url' => 'https://name.myserver.com',
'overwriteprotocol' => 'https',
```

![notes-https](https://user-images.githubusercontent.com/1963922/83077498-d3039080-a077-11ea-9d46-0c29162c5f1d.png)

In the other hand the result of network analysis console is the same but I don't know if is dangerous for the security of site and connection.

**Comment by korelstar** [comment] 2020-05-31 08:39
Closing because it's a server configuration issue (and not about the Notes app). Please use the [forum](https://help.nextcloud.com/) for going into further details.

**Closed by korelstar** 2020-05-31 08:39 UTC
