### ISSUE TITLE
Ability to join files likes screenshots or photos

### ISSUE THREAD

**Issue by tclavier** [nextcloud/notes#294] opened 2019-01-19 08:10 UTC
As a user I want to attach some files to my notes. For exemple, I wrote a markdown note, and I want to add a photo. I can choose a photo in my nextcloud gallery or upload a new one. After that I see the markdown IMG link in my note.

**Comment by korelstar** [comment] 2019-01-19 08:48
Duplicate of #74

**Comment by korelstar** [comment] 2019-01-19 08:49
Please feel free to increase the bounty on #74. :-)

**Closed by korelstar** 2019-01-19 08:48 UTC
