### ISSUE TITLE
Nextcloud notes hangs after creating a new note

### ISSUE THREAD

**Issue by godfuture** [nextcloud/notes#536] opened 2020-06-07 22:37 UTC
If I create a new note, the "new note spinner" is active quite a long time. Up to multiple minutes. After some time I get:
`Fehler
Auf den Notizordner kann nicht zugegriffen werden: "Notes/Neue Notiz.txt" is locked
Bitte wähle einen geeigneten Verzeichnispfad in den Einstellungen (unten links).`

Deleting is taking ages as well. The spinner is active for many minutes. After some time, I get:
`Auf den Notizordner kann nicht zugegriffen werden: "Notes/Neue Notiz.txt" is locked`

After some time, NC behaves normal again. New notes appear immediately, deleting them is no problem, as it happens instantly. But when navigating to some other NC app (e.g. calendar) and back, the trouble starts again.

NC notes: 3.5.0
NC: 18.0.5

**Comment by korelstar** [comment] 2020-06-08 06:25
Which [memory caching](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/caching_configuration.html) configuration do you use?

**Comment by korelstar** [comment] 2020-06-08 06:43
Is there some additional information in your nextcloud.log? E.g. an exception with stack trace?

**Comment by godfuture** [comment] 2020-06-09 18:57
> Which [memory caching](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/caching_configuration.html) configuration do you use?

  'memcache.local' => '\\OC\\Memcache\\APCu',
  'filelocking.enabled' => 'true',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'redis',
    'port' => 6379, 
  ),

**Comment by korelstar** [comment] 2020-06-11 19:21
I tried to reproduce this issue using your memory caching configuration, but the problem did not occurred to me. Please provide more information about your setup: Operating system, middleware, hardware etc. for both client and server. Do you have a distributed server setup with multiple HTTP servers? Is redis running on another machine?

Maybe you can reduce your setup to one single server an disable the distributed memory cache (and maybe other configuration options?) temporarily, in order to find the origin of this problem.

**Comment by korelstar** [comment] 2020-07-15 11:45
Closing due to missing feedback. We can re-open this issue when the needed information is provided.

**Closed by korelstar** 2020-07-15 11:45 UTC
Labels: needs info
