### ISSUE TITLE
Feature Request: Configurable Storage Path

### ISSUE THREAD

**Issue by benyanke** [nextcloud/notes#171] opened 2018-02-21 06:28 UTC
It's all in the title. Could be as simple as a single text field in the admin panel.

**Comment by jdunn0** [comment] 2018-03-07 02:34
I just looked at the source code and it appears the private function `getFolderForUser` in file `notes/service/notesservice.php` is where a change would need to happen to allow a different storage path.
I'll have to test it but it appears changing the code in the function from `$path = '/' . $userId . '/files/Notes';` to `$path = '/' . $userId . '/files/custom_notes_directory';` would be all that is required to change the folder from 'Notes' to 'custom_notes_directory' instead.

I'll have to test this later to see if that works as there might be other files that reference the path but if not then making the function return an administrator assigned path instead of a fixed path should be fairly easy.

**Comment by korelstar** [comment] 2018-04-04 19:25
Duplicate of #57

**Closed by korelstar** 2018-04-04 19:25 UTC
Labels: duplicate
