### ISSUE TITLE
Notes doesn't display photos when it is inside Nextcloud

### ISSUE THREAD

**Issue by hrv231** [nextcloud/notes#729] opened 2021-06-15 22:04 UTC
Please make a clear and concise description of what the bug is. Please note, that issues with the Android app have to be reported under https://github.com/stefan-niedermann/nextcloud-notes/issues and issues with Nextcloud's Text app have to be reported under https://github.com/nextcloud/text/issues .

## Steps to reproduce
1. Insert an image to a .md file via Nextcloud files (nextcloud text)
2. Open the same .md file on Notes

### Expected behaviour
I should be able to see the image that was inserted using Nextcloud files editor

### Actual behaviour
I get this instead:
`![pixel_3a_test](InstantUpload/Download/pixel_3a_seethrough_1.jpg?fileId=66864#mimetype=image%2Fjpeg&hasPreview=true)`

### Screenshots
Files editor
![Nextcloud files](https://user-images.githubusercontent.com/41212308/122126766-1184fe00-cde7-11eb-8386-affb753c49a2.png)
Notes
![Nextcloud notes](https://user-images.githubusercontent.com/41212308/122126723-ff0ac480-cde6-11eb-8fb5-ef9b4add98b5.png)

## Server
Please complete the following information.

- Notes app version: 4.0.4
- Nextcloud version:  20.0.8
- OS: Docker
- Web server: 
- PHP version: 
- Database: mysql  Ver 15.1 Distrib 10.4.19-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**Nextcloud configuration:**

<details>
```
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "10.10.100.55",
            "myserver.duckdns.org"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.8.1",
        "overwrite.cli.url": "https:\/\/myserver.duckdns.org",
        "overwritehost": "myserver.duckdns.org",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    }
}
```
</details>

## Client
Please complete the following information.

- Browser (incl. version): Firefox 89.0 (64-bit)
 - OS: Windows 10

## Log files
Add relevant parts of your `nextcloud.log` and/or your browser's JavaScript console here.

**Comment by korelstar** [comment] 2021-06-17 00:24
Duplicate of #74

**Closed by korelstar** 2021-06-17 00:24 UTC
Labels: bug, need to reproduce
