### ISSUE TITLE
Add option to show only rendered markdown

### ISSUE THREAD

**Issue by iandk** [nextcloud/notes#312] opened 2019-05-21 09:34 UTC
**Describe the solution you'd like**
Especially the code blocks are rather impractical to work with, therefore it would be great if you could toggle the view, that you only get the rendered markdown as an output, without e.g. the code tags  "```"

**Comment by korelstar** [comment] 2019-05-21 11:17
Duplicate of #23

**Closed** 2019-05-21 11:18 UTC
Labels: discussion, enhancement
