### ISSUE TITLE
Integrity Check fails

### ISSUE THREAD

**Issue by treuss** [nextcloud/notes#145] opened 2017-10-27 13:12 UTC
Hi,

since I installed Nextcloud Notes v2.3.1, I get the following warnings for failed integrity checks:

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- notes
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- App Certificate is not valid.

Raw output
==========
Array
(
    [notes] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => App Certificate is not valid.
                )

        )

)
```

How can I resolve this issue?

I'm running the following setup:

- OwnCloud version: 10.0.0.3
- OS version: Raspbian 8 (Jessie)
- PHP version: 5.6.30

Best regards
Thomas

**Comment by korelstar** [comment] 2017-10-27 13:22
Duplicate of #140

**Closed by korelstar** 2017-10-27 13:22 UTC
Labels: duplicate
