### ISSUE TITLE
File extension

### ISSUE THREAD

**Issue by Marcatquod** [nextcloud/notes#160] opened 2018-01-06 17:13 UTC
Now, the default file extension when creating a note is **.txt**.

It would be great if it is **.md** to be directly and fully usable with the MarkDown app (or maybe if we can choose the file extension when creating a new note)

Thanks for this great app !
Marc

**Comment by marcelstoer** [comment] 2018-01-09 20:08
I suggest to close this as PR #153 will include a fix for this.

**Comment by korelstar** [comment] 2018-04-04 19:17
Duplicate of #24

**Closed by korelstar** 2018-04-04 19:17 UTC
Labels: duplicate
