### ISSUE TITLE
An error occured when searching notes

### ISSUE THREAD

**Issue by rightsaidfred99** [nextcloud/notes#871] opened 2022-06-03 00:51 UTC
Please make a clear and concise description of what the bug is. Please note, that issues with the Android app have to be reported under https://github.com/stefan-niedermann/nextcloud-notes/issues and issues with Nextcloud's Text app have to be reported under https://github.com/nextcloud/text/issues .

## Steps to reproduce
1. limit plugin to a certain group ie Admins
2. on another account, that is not Admin, go to the search bar and literally type anything
3. one will receive many errors saying "An error occurred while searching for Notes✖"

### Expected behaviour
An error occurred while searching for Notes✖ should not happen if user has no access to the plugin

### Actual behaviour
An error occurred while searching for Notes✖ appears flooding the screen

## Server
Please complete the following information.

- Notes app version: 
- Nextcloud version: 
- OS: 
- Web server: 
- PHP version: 
- Database: 

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

## Client
Please complete the following information.

- Browser (incl. version): 
 - OS: 

## Log files
Add relevant parts of your `nextcloud.log` and/or your browser's JavaScript console here.

**Comment by korelstar** [comment] 2022-08-05 16:18
I can't reproduce this issue. However, If I do a search with a user that is excluded from using the notes app, the search nevertheless shows results for the notes app. This shouldn't be the case. I did the test with Nextcloud 24.0.3 and Notes 4.4.0.

However, I don't think this is a bug of the notes app. Instead, the Nextcloud server search should not search in the Notes app, if the user is not allowed to use the Notes app. This has to be fixed in Nextcloud server, since it affects all apps (I tested it also with the Deck app). Please check for existing issues in the Nextcloud server repository and create a new one, if there is none.

**Closed by korelstar** 2022-08-05 16:18 UTC
Labels: bug, need to reproduce
