### ISSUE TITLE
Customizable Path for each category individually

### ISSUE THREAD

**Issue by Nawrux** [nextcloud/notes#1125] opened 2023-10-03 23:51 UTC
**Is your feature request related to a problem? Please describe.**
I want to sort my notes in diffrent folder, like Personal/notes and work/notes.
Currently its like Notes/Personal and Notes/Work.
It would be easier to share Work related notes and data by just sharing the work folder and not share two folders (Work and Notes/Workd). 

**Describe the solution you'd like**
I would like to have an option to change the path of each category individually

**Comment by stefan-niedermann** [comment] 2023-10-04 06:47
Duplicate of https://github.com/nextcloud/notes/issues/670

**Comment by joshtrichards** [comment] 2024-08-08 14:12
(just closing; was previously marked as a duplicate but closure was overlooked)

**Closed** 2024-08-08 14:12 UTC
Labels: needs discussion, feature request
