### ISSUE TITLE
Sharing and Formatting Implementation

### ISSUE THREAD

**Issue by talesam** [nextcloud/notes#779] opened 2021-11-14 17:40 UTC
I've said this before, I like and use Notes a lot, but I see there are things that already exist in Nextcloud's code that can be incorporated into Notes, such as Nextcloud's default text application, which has a lot of formatting. simple form that can be inserted into the text, as in the image below:
![Captura de tela de 2021-11-14 14-36-40](https://user-images.githubusercontent.com/981368/141692015-afa54875-0eec-4d29-a2e4-653c96287f10.png)

Sometimes I want to share a note with a friend and there is no option, just in the mobile app which is actually a [ctrl+c] [ctrl+v].

If Notes had the features that this simple text editor has, it would be closer to the keeps, which is actually this Nextcloud text editor in notes format.

**Comment by stefan-niedermann** [comment] 2021-11-14 17:48
Please use the 🔍 search function before opening new issues. Each of your requests has already gone through a ton of dicussions, duplicating them and continuing them on different issues will make the trouble even worse.

> there are things that already exist in Nextcloud's code that can be incorporated into Notes, such as Nextcloud's default text application

Duplicate of https://github.com/nextcloud/notes/issues/331

> I want to share a note with a friend and there is no option

Duplicate of https://github.com/nextcloud/notes/issues/38

You are welcome to read *completly* trhough the linked issues and then append further input and ideas to them. You can also start pull requests for concrete implementations. Feel free to upvote them. Please do **not** jump to the linked issues and comment "me too" though.

**Closed by stefan-niedermann** 2021-11-14 17:48 UTC
Labels: needs discussion, feature request
