### ISSUE TITLE
Correct display of checklist items in preview/markdown mode is swapped

### ISSUE THREAD

**Issue by owzim** [nextcloud/notes#753] opened 2021-08-31 17:44 UTC
Brackets `[]` are displayed as checkboxes in markdown mode and as brackets in preview mode. But it should be the other way around.

## Steps to reproduce

1. create a new note
2. add a list:
   ```md
   - [ ] foo bar
   - [ ] bar baz
   - [ ] baz qux
   ```
3. toggle between preview and markdown mode

#### Markdown mode:

brackets are incorrectly displayed as checkboxes, should be brackets

![image](https://user-images.githubusercontent.com/1720088/131549820-13a4b285-961c-4d07-b48d-d8b761c059b2.png)

#### Preview mode:

brackets are incorrectly displayed as brackets, should be checkboxes

![image](https://user-images.githubusercontent.com/1720088/131549956-7c18b497-116c-4fb2-8942-5bd65a474bd3.png)

## Server
Please complete the following information.

- Notes app version:  4.1.1
- Nextcloud version: 21.0.4
- OS: Linux 3.10.0-1160.31.1.el7.x86_64 x86_64
- Web server: Apache
- PHP version: 7.3.29
- Database: mySQL 10.3.27

## Client
Please complete the following information.

- Browser (incl. version): Firefox 91.0.2 (64-bit)
- OS: macOS 10.14.6

**Comment by stefan-niedermann** [comment] 2021-08-31 17:48
Please use the 🔍 search function before opening new issues.

Closing as duplicate of https://github.com/nextcloud/notes/issues/325

**Closed by stefan-niedermann** 2021-08-31 17:48 UTC
Labels: bug, need to reproduce

**Comment by owzim** [comment] 2021-08-31 17:55
@stefan-niedermann I am deeply sorry. Will do in the future =)
