### ISSUE TITLE
Version 2.4.2 requests NC version 13 or lower

### ISSUE THREAD

**Issue by deadwax** [nextcloud/notes#261] opened 2018-10-03 12:01 UTC
Notes will not enable in NC 14.0.1 as a result, with Nextcloud reporting version 13 or lower required.

Installed from store, where it is shown that 2.4.2 will work with NC 14.

**Comment by deadwax** [comment] 2018-10-03 12:12
Temporarily fixed by changing max version in info.xml from 15 to 14.  15 does not appear to be a valid value.

Don't know how to use github, not a programmer sorry, so can't make the fix for everyone.

**Comment by n1try** [comment] 2018-10-05 01:04
I can't reproduce this. Can you give some further instructions?

Also, when `max-version` is 15, why would it not be compatible with 14.x.x ?

**Comment by Jaczel** [comment] 2018-10-08 01:59
Not sure what the cause of the issue is but I can confirm that Nextcloud 14 does not support the current version of Notes that is on the Store.

**Comment by korelstar** [comment] 2018-10-08 05:28
Does de-installing an reinstalling help?

**Comment by deadwax** [comment] 2018-10-08 06:41
I had notes 2.4.2 installed on Nextcloud 13.  Upon upgrade to NC 14 notes was disabled and the error was as above "Server version 13 or lower is required."

Changing max versions to 14 fixed it, as noted above.

I did not try uninstalling.

**Comment by korelstar** [comment] 2018-10-08 19:26
I tried to reproduce this and did the same steps as you wrote, but everything works fine, here. Honestly, I can't imagine, that the number `15` is a problem. Maybe it was a (PHP) caching problem? Please try the following:

- Change `max-version` back to 15, deactivate the app and try to activate it again. Does this work?
- Remove the directory `apps/notes/` and its contents from the server's filesystem and re-install the app from the store. Does this work?
- What's the result of executing `occ integrity:check-app notes` on the server?

Thanks for your help.

**Comment by Jaczel** [comment] 2018-10-11 21:51
> Not sure what the cause of the issue is but I can confirm that Nextcloud 14 does not support the current version of Notes that is on the Store.
> The message provided on the Nextcloud Apps Store is:
> 
> ```
> This app cannot be installed because the following dependencies are not fulfilled:
>     Server version 13 or lower is required.
> ```

I just rebooted my server and enabled the Notes app with no problems. Not sure what was going on the first time round but everything seems fine now.
Note: I had not rebooted my server initially after upgrading to Nextcloud Version 14. This is the first reboot since upgrading.

**Comment by StaffanMelin** [comment] 2018-10-13 06:27
I had the same problem, and can confirm that rebooting my server fixed the issue. I can now install and enable Notes (and Tasks) w/o any problems.

**Comment by korelstar** [comment] 2018-11-11 10:40
Does anybody still have this problem? Otherwise, I would like to close this issue.

**Comment by korelstar** [comment] 2018-11-17 15:33
Just released v2.5.0. Please try it with this version, @deadwax

**Closed** 2018-11-28 15:59 UTC
Labels: needs info
