### ISSUE TITLE
Checkbox is shown in edit mode, not in preview mode

### ISSUE THREAD

**Issue by goett2win** [nextcloud/notes#757] opened 2021-09-10 13:03 UTC
When I draw a checkbox via `* [ ]` mode instead of in preview mode. This should be switched, I guess.

## Steps to reproduce
1. Create a note
2. Type `* [ ]`

### Expected behaviour
**the symbol should be shown in preview mode**

### Actual behavior
**the symbol is shown in edit mode**

## Server
Please complete the following information.

- Notes app version: 4.0.4.
- Nextcloud version: 20.0.12.
- OS: Ubuntu
- Web server: apache2
- PHP version: 7.2.24
- Database: mysql 10.1.47

## Client
Please complete the following information.

- Browser (incl. version): Firefox 91.0.2
- OS: Ubuntu 20.04

**Comment by stefan-niedermann** [comment] 2021-09-10 13:05
Please use the 🔍 search function before opening new issues.

Closing as duplicate of https://github.com/nextcloud/notes/issues/325

**Closed by stefan-niedermann** 2021-09-10 13:05 UTC
Labels: bug, need to reproduce
