### ISSUE TITLE
new note nextcloud-desktop sync error

### ISSUE THREAD

**Issue by moolow** [nextcloud/notes#318] opened 2019-06-06 15:50 UTC
**Describe the bug**
A clear and concise description of what the bug is. Please note, that issues with the Android app have to be reported under https://github.com/stefan-niedermann/nextcloud-notes/issues

**To Reproduce**
1. Go to 'Notes App'
2. Click on 'Create New empty memo'
3. sync auto nextcloud-desktop

**Expected behavior**
Success sync empty memo

**Screenshots**
1. Create New empty memo
![스크린샷, 2019-06-07 00-31-36](https://user-images.githubusercontent.com/10431136/59046613-463b5200-88bd-11e9-8497-e49da0a0b0d9.png)
2. nextcloud-desktop 2.5.1-2 activity log
![스크린샷, 2019-06-07 00-30-57](https://user-images.githubusercontent.com/10431136/59046632-4f2c2380-88bd-11e9-882d-409f3eb365aa.png)

**Server (please complete the following information):**
- Notes app version: 2.6.0
- Nextcloud version: 15.0.8snap2
- OS: ubuntu 19.04
- Web server: Apache 2.4
- PHP version: 7.2
- Database: 5.7

**Client (please complete the following information):**
 - Browser (incl. version): firefox 67
 - OS: ubuntu 19.04

**Log files**
Add relevant parts of your `nextcloud.log` and/or your browser's JavaScript console here.

**Comment by korelstar** [comment] 2019-06-06 20:02
Thanks for reporting this issue. Since the error appears in the desktop client, I'm not sure if the cause is really the notes app. The notes app just creates a file.

What happens if you manually create an empty file with that name? (Please be aware that creating a new text file using the files app may create a file with a single space character!)
Did you reported this issue in the [desktop client repository](https://github.com/nextcloud/desktop)?

**Comment by korelstar** [comment] 2019-08-20 18:27
Closing due to missing feedback.

**Closed by korelstar** 2019-08-20 18:27 UTC
Labels: needs info

**Comment by drikqlis** [comment] 2020-02-14 14:22
Hi, I have the same problem. It occurs only with empty notes created in Notes on web. I can create empty note with Files and in Windows Explorer and there is no sync error. It is a minor problem but very confusing for end users.
