### ISSUE TITLE
NC26: First run of the Notes app after upgrading to NC26 runs a modal dialogue which does nothing

### ISSUE THREAD

**Issue by thopanX** [nextcloud/notes#988] opened 2023-03-22 18:19 UTC
## Steps to reproduce
1. Update/Install Nextcloud Hub 4
2. Navigate in the web browser to the notes app
3. Experience an automatic forwarding to a note (here 49956) and a modal dialogue about a choice between Markdown and rich-text editor 

### Expected behaviour
Clicking one of the buttons in the open modal dialogue or the x should close the modal and return to the notes app

### Actual behaviour
Clicking any of the buttons does nothing, clicking the x to close the note leaves the background dimmed and inaccessible. I cannot access the notes app.

This happens with my user account which has notes, but not with my admin account which has no notes.

### Screenshots

![grafik](https://user-images.githubusercontent.com/1814897/226998841-095b4615-6391-48e5-b776-ca5e492e7731.png)

## Server
Please complete the following information.

- Notes app version: 4.7.1
- Nextcloud version: 26.0.0
- OS: Linux 3.10.0-1160.83.1.el7.x86_64 x86_64
- Web server: Apache
- PHP version: 8.0.28
- Database:  mysql 10.6.12

## Client
Please complete the following information.

- Browser (incl. version): 
 - OS: Firefox 110

**Comment by jakobroehrl** [comment] 2023-03-22 18:31
duplicate of https://github.com/nextcloud/notes/issues/982

**Closed by jakobroehrl** 2023-03-22 18:31 UTC
Labels: bug, need to reproduce

**Comment by jakobroehrl** [comment] 2023-03-22 18:44
no problem! :)
