### ISSUE TITLE
Delay fetching notes via API

### ISSUE THREAD

**Issue by sciurius** [nextcloud/notes#589] opened 2020-08-22 18:49 UTC
**Describe the bug**
When I fetch a note (or note information) using the API, there seems to be a 2-3 second delay. This is consistent, independent of server load, so it may indicate some internal time-out

**To Reproduce**
1. Use curl to fetch note info, e.g. `curl -u "user:password" https://cloud.squirrel.nl/index.php/apps/notes/api/v1/notes/141980
2. Response after 3 seconds.

**Expected behavior**
Output within a reasonable amount of time. Since this is a lightly loaded server on a local LAN I'd expect a response in milliseconds.

**Server (please complete the following information):**
- Notes app version: 3.6.2
- Nextcloud version: 19.0.1
- OS: Raspbian
- Web server: nginx
- PHP version: 7.3
- Database: PostgreSQL

**Client (please complete the following information):**
 - Browser (incl. version): curl 7.66.0
 - OS: Fedora 31

**Log files**
A message similar to this is written to the NC log for each request:
````
{"reqId":"c4dvydfNm08qhTtBCKb2","level":3,"time":"2020-08-22T18:35:38+00:00","remoteAddr":"192.168.1.251","user":"--","app":"PHP","method":"GET","url":"/index.php/apps/notes/api/v1/notes?exclude=content","message":"session_start(): A session had already been started - ignoring at /var/www/nextcloud/lib/private/Session/Internal.php#209","userAgent":"curl/7.66.0","version":"19.0.1.1"}
````

**Comment by korelstar** [comment] 2020-08-25 18:47
I can confirm this. However, I don't know when this was introduced. Recently, I did some work in order to improve the speed, see https://github.com/nextcloud/notes/pull/525 (Notes app 3.5.0). I remember, that I measured a time of around 200ms for API requests. However, I don't remember the exact Nextcloud server version. I think it was something in 18. Now, with Nextcloud server 19 and Notes 3.6.3, I get something around 2.200 ms.

Hence, we have to investigate in which version of Nextcloud server or the Notes app the slowness was introduced.

I did a quick test on this using Nextcloud's docker images, but I couldn't find any difference between versions. Any help is appreciated, since it seems to be a time consuming investigation.

**Comment by korelstar** [comment] 2020-08-25 18:47
Oh, and you can safely ignore the session error message. It's a bug in Nextcloud server (see https://github.com/nextcloud/server/issues/20490) which was fixed in https://github.com/nextcloud/server/pull/22243 (will be part of 19.0.2).

**Comment by sciurius** [comment] 2020-08-25 20:22
There are similar delays when using webdav so the problem may be more general.

**Comment by korelstar** [comment] 2020-10-01 19:01
Interestingly, I can't see a delay anymore, when using the Android App. However, when doing a request using `curl`, it still takes about 2 seconds (even in my test account with very few notes).

Does the problem still occurs to you with the latest server version?

**Comment by stefan-niedermann** [comment] 2020-10-01 19:53
@korelstar maybe the `ETags` distort the results from the Android App... I guess you make full requests without `If-Modified-Since` headers and such stuff, maybe this causes (or prevents) the delay?

**Comment by korelstar** [comment] 2020-10-01 20:49
No, I used ETags (`If-None-Match`) and `pruneBefore`. But I had no time to dig into the details ...

**Comment by korelstar** [comment] 2022-01-15 09:18
In practice, I can't see any delay since a long time. I'll close this issue for now. If it will happen again, we can re-open it.

**Closed by korelstar** 2022-01-15 09:18 UTC
