### ISSUE TITLE
Web creation + immediate renaming of a note causes a synchronization error in Nextcloud clients

### ISSUE THREAD

**Issue by Kalytis** [nextcloud/notes#900] opened 2022-08-14 15:47 UTC
## Steps to reproduce
1. Having Nextcloud Server with Notes installed + Nextcloud sync clients on computers.
2. Create a note on Nextcloud Notes via web interface
3. Immediately renaming the note

### Expected behaviour
Pretty much nothing, the note should save and synchronize right away.

### Actual behaviour
A synchronization error occurs when the "New note.txt" was added to sync queue but didn't have time to complete sync before it was renamed by user on web interface.

## Server
Please complete the following information.

- Notes app version: 4.5.0
- Nextcloud version: 24.0.3
- OS: Ubuntu Server 22.04.1
- Web server: Nginx
- PHP version: 8.0
- Database: MySQL

**Nextcloud configuration:**

<details>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "24.0.3.2",
        "overwrite.cli.url": "***REMOVE SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "updater.release.channel": "beta",
        "theme": "",
        "loglevel": 2
    }
}

</details>

## Client
Please complete the following information.

- Browser (incl. version): Firefox 103.0.2
- OS: Ubuntu 22.04.1

**Comment by korelstar** [comment] 2022-08-14 19:52
I cannot reproduce this. But I don't think there is anything we can do in the Notes app regarding this issue. It looks like this is a problem with the Nextcloud sync client. Do you have done an issue search in that repository? By the way: what's the exact error message (a screenshot would be helpful)? And another question just for understanding: Step 3 is done also via web browser using the Notes app?

**Comment by Kalytis** [comment] 2022-08-17 13:38
I haven't searched it. I'll try to catch the error message.

And yes, step 3 is via web browser.

**Comment by korelstar** [comment] 2022-10-01 19:53
Closing due to missing feedback. If the issue still occurs, please open an issue in the Nextcloud sync client's repository.

**Closed by korelstar** 2022-10-01 19:53 UTC
Labels: bug, needs info, need to reproduce
