### ISSUE TITLE
Search the whole text of note (not only the title)

### ISSUE THREAD

**Issue by florom** [nextcloud/notes#641] opened 2020-12-01 09:22 UTC
Hi Devs,

I'm always frustrated when I try to search for a specific note but only the text in title would match. So for example I usally copy/paste text into a note so I have them later. I usally do not want to care what the title ist sometimes its meaninful sometimes not. So when I  know that there is a specific word in the textbody I want to search trough every text not only the notes.

Using the search inside of notes will match with title and textbody.
Using the search in the nextcloud taskbar uses Titel and text or title only (frankly I do not care)

You can do it with windows and in the android app it is possible too  (please do not remove that) but integrated in the notes app would be much better and more comfortable.

I guess it only makes sense in notes where there are per definition only text files.

Thank you for considering.

PS: Great App - I use it in the personal production (I have to nextclouds one with allmost every app and one with only a few which are the most needed and secure)

**Comment by stefan-niedermann** [comment] 2020-12-01 09:29
Duplicate of https://github.com/nextcloud/notes/issues/288
Fixed in https://github.com/nextcloud/notes/pull/600

With NC 20 & Notes 4.0.0 the content will be searched, too.

**Closed by stefan-niedermann** 2020-12-01 09:29 UTC
Labels: feature request

**Comment by stefan-niedermann** [comment] 2020-12-01 09:30
> in the android app it is possible too (please do not remove that)

I won't remove that 🤣

**Comment by florom** [comment] 2020-12-01 10:02
Perfect :)
