### ISSUE TITLE
Change default view to "Preview" instead of "Edit".

### ISSUE THREAD

**Issue by emkamau** [nextcloud/notes#741] opened 2021-07-31 00:16 UTC
**Is your feature request related to a problem? Please describe.**
By default notes are displayed in the app in "Edit" mode this makes it difficult to read notes created in Markdown as they are displayed with the markdown code visible. This requires the extra steps of turning off the markdown code by clicking on the "..." menu and selecting "preview".

**Describe the solution you'd like**
When you click on a note in the listing the contents of the note should display properly formatted without showing the formatting code (in this case Markdown code). Most of the time When I look at my notes my intention is to read them and not to edit them so I think the most readable view should be the default mode of display.

**Describe alternatives you've considered**
None really.

**Additional context**
### Current default view for Markdown notes:
![notes-display-1](https://user-images.githubusercontent.com/26052014/127722519-a973a44c-c638-4817-9cc9-5a541d170e15.jpg)

### Proposed default view for Markdown notes:
![notes-display-2](https://user-images.githubusercontent.com/26052014/127722523-0f74c3c3-03f7-4a8c-a0e6-4f1aa883b8f0.jpg)

**Comment by korelstar** [comment] 2021-07-31 08:01
Duplicate of #352

**Closed by korelstar** 2021-07-31 08:01 UTC
Labels: feature request, needs discussion
