### ISSUE TITLE
Add Color to categories

### ISSUE THREAD

**Issue by aproposnix** [nextcloud/notes#461] opened 2020-02-09 08:34 UTC
**Describe the solution you'd like**

As a user, I would like to be able to color my categories. 
On the Android app, the category badge in the notes list is always the same color (blue on my phone) no matter which category it is.  When I am viewing all notes, it would be nice to be able to visually distinguish categories by color.

**Comment by stefan-niedermann** [comment] 2020-02-09 09:19
Duplicate of #10

**Closed by stefan-niedermann** 2020-02-09 09:19 UTC
Labels: feature request
