### ISSUE TITLE
Obsidian-like internal links support in markdown

### ISSUE THREAD

**Issue by MayneX** [nextcloud/notes#889] opened 2022-08-04 02:41 UTC
**Is your feature request related to a problem? Please describe.**
Usually my notes contain many internal links between each other, that are not supported by Nextcloud notes. It makes almost impossible using of this tool for many my friends and me.

**Describe the solution you'd like**
1. Links in double brackets should be linkable (e.g. [[internal link]])
2. If document is not found after a click, the new document has to be created
3. Internal links should support different use of links for languages with many "cases"

**Describe alternatives you've considered**
Sorry, I can't see usable alternative.

**Additional context**
Example of using internal links in Obsidian using different case for display
<img width="538" alt="Example" src="https://user-images.githubusercontent.com/1284303/182751298-fc690604-6a69-4d6b-b030-57672cfa03ec.png">

**Comment by korelstar** [comment] 2022-08-04 07:14
Duplicate of #616

**Closed** 2022-08-05 09:11 UTC
Labels: needs discussion, feature request
