### ISSUE TITLE
Web interface, no categories (folders), mobile interface, shows them.

### ISSUE THREAD

**Issue by BloodyIron** [nextcloud/notes#249] opened 2018-08-25 15:09 UTC
Hey, so, when I go to the folder (in the files "app") for the Notes section, make a new sub-folder, and move some notes into it, the mobile Notes app (android) does see that they are "categorised", however the web interface (via nextCloud itself), does not show any such categorisation.

Any chance we can get this feature parity going on? I also can't seem to find a way to make new categories in the web interface, and the mobile interface, can't quite figure out a way to move notes into existing categories, just click hold with delete option, no move.

Please? :)

**Comment by korelstar** [comment] 2018-08-26 15:32
Duplicate of #8.

Please have a look at #210 and #228 for the current implementation progress.

**Closed by korelstar** 2018-08-26 15:32 UTC
