### ISSUE TITLE
full-text search

### ISSUE THREAD

**Issue by tobifree** [nextcloud/notes#509] opened 2020-05-16 06:44 UTC
**Is your feature request related to a problem? Please describe.**
I like your app pretty much and found it to be a simple solution to collaboratively keep track of the results of my group's meetings. In order to work well, we need full-text search in this app. 

**Describe the solution you'd like**
The search results should not only cover the note's titles in the left side bar, but also the actual note's texts as results (optionally with highlighting) in the main frame.

**Describe alternatives you've considered**
There's no alternative to full-text search ;)

**Additional context**
The Nextcloud Notes app for Android already features full-text search.

**Comment by stefan-niedermann** [comment] 2020-05-16 06:58
Is this a duplicate of #288

**Comment by korelstar** [comment] 2020-05-16 10:28
Duplicate of #288

**Closed by korelstar** 2020-05-16 10:28 UTC
Labels: feature request
