### ISSUE TITLE
Error after last update: notes folder is not accessible

### ISSUE THREAD

**Issue by Japhys** [nextcloud/notes#546] opened 2020-06-17 08:43 UTC
Notes 3.51
Nextcloud 18.06

After update to 18.06 out of the blue my notes won't open anymore.

This is the error I get:

The notes folder is not accessible: Bad Signature✖

![Screenshot(45)](https://user-images.githubusercontent.com/24695937/84876292-59affa00-b087-11ea-849f-82c3d14e0188.png)

**Comment by korelstar** [comment] 2020-06-17 20:40
Are you able to open your notes folder using the files app?

Please check also you server nextcloud.log. Is there an exception or something?

And finally: please provide more information about your setup (see issue template; it isn't there just for fun!), especially about the encryption setup.

**Comment by Japhys** [comment] 2020-06-18 15:11
**Describe the bug**
Notes will not show when clicking Ntoes from the admin bar. When I browse my folder, the folder Notes is accessible

**To Reproduce**
Steps to reproduce the behavior:
1. Go to menu Notes
2. Error appears

**Expected behavior**
I expect to see my notes

**Screenshots**
See screenhots

**Server (please complete the following information):**
- Notes app version: 1.5.1
- Nextcloud version: 18.06
- OS: Linux 18.04 LTS
- Web server: Apache 2.4
- PHP version: 	7.2.24
- Database: mysql 10.1.44

**Client (please complete the following information):**
 - Browser (incl. version): Firefox 77.01
 - OS: Windows

**Log files**

![2020-06-18_170351](https://user-images.githubusercontent.com/24695937/85038204-9c0c3080-b186-11ea-8df4-a97801fb812d.jpg)

**Comment by korelstar** [comment] 2020-06-19 12:25
Looks like there is an issue regarding the encryption with at least one file in your account. The exception you've posted includes the file name. Please try to move that file into a directory outside of your notes folder and try again.

Since you wrote that the issues happened after updating Nextcloud server, I think you should open an issue ticket in the server repository.

**Comment by BloodyIron** [comment] 2020-06-19 23:21
I too have a broken notes app with the recent update, same error in the web interface. But I'm not using encryption on files. Pretty sure this is a regression here.

This issue happened only after updating the Notes plugin.

**Comment by korelstar** [comment] 2020-06-20 05:50
@BloodyIron Please provide more information on this (used versions etc, see issue template). Are there any relevant entries in the log file?
Do you really get a "Bad signature" error? This doesn't make any sense if you are not using encryption.

**Comment by BloodyIron** [comment] 2020-06-21 14:17
Okay so I checked the nextcloud.log file, and it was complaining about a text file that no longer existed, but showed up in the Files section of nextCloud. So I deleted in the Files scope, and now Notes works. I can even sync with my android Notes app too. How curious, I wonder how that happened.

**Comment by Japhys** [comment] 2020-06-21 15:35
> 
> 
> Looks like there is an issue regarding the encryption with at least one file in your account. The exception you've posted includes the file name. Please try to move that file into a directory outside of your notes folder and try again.
> 
> Since you wrote that the issues happened after updating Nextcloud server, I think you should open an issue ticket in the server repository.

I tried to move all files from the log entries but still get this error. Worrisome. I will indeed open an issue in the NC repository

**Comment by korelstar** [comment] 2020-06-21 19:28
Thanks for the feedback.

Since the problem by @BloodyIron is fixed and @Japhys created an issue in https://github.com/nextcloud/server/issues/21515, I'm closing this for now.

**Closed by korelstar** 2020-06-21 19:28 UTC
