### ISSUE TITLE
decouple note title from first line of contents

### ISSUE THREAD

**Issue by brainchild0** [nextcloud/notes#289] opened 2019-01-08 08:51 UTC
Having reviewed #24, #55, and #190, I am surprised that the Notes app has taken a different approach from similar projects concerning note naming.  I fear many users will, as I do, find the behavior confusing as well as limiting.  

In similar environments, when a new note is added, the title is derived from the first line of text, unless one is given explicitly in a separate text box provided for that purpose.  Notes can always be retitled, in such a design, whether the title was given by the user or generated automatically.  

Indeed, this behavior would also conform more closely to the model employed in the app, in which notes are simply files.  Then the name and contents of the file are independent data.  One benefit of notes being files is that the notes can easily be read by external application, including desktop applications on clients that synchronize to the Nextcloud instance.  These files may, however, be processed in such a way that the contents of the file and the name of the note should not be interdependent.  In the current model, the user must choose between beginning the file contents with a title line that would otherwise be omitted, for the sake of making the title be listed as desired, or having the title set to whatever the first line of the contents happens to be.  Thus, the current model actually limits, in my view, the benefit of notes being files.

(For example, I was experimenting with using the Notes app to write a document.  My document is processed into a published format on my desktop system, and the file is synchronized via the Nextcloud desktop synchronization client.  But my processing software adds the document title separately, so it is detrimental if the document title is the first line of the file, rather than the first section header being the first line.  But of course this constraint is a conflict because Notes then sets the note title to the section header, not the title I have chosen for the document.  In this case, I have a perfectly good intended format for the file contents, except that it does not integrate well with the Notes app.  Meanwhile, if I could use the Notes app to write the document, it is very convenient, as I can make incremental changes from browser, desktop application, or mobile device.)

I believe I understand the sensibilities behind the previous decision, but wonder if ultimately it may be limiting and confusing.  Perhaps the core development team would like to keep in mind these considerations as the project design evolves.

**Comment by korelstar** [comment] 2019-01-08 12:10
Duplicate of #190

**Comment by korelstar** [comment] 2019-01-08 12:18
I agree, but all that was already discussed. The issue #190 is still open and we wrote there that we are willing to change this behaviour. Any further discussion should be done in #190. Please feel free to increase the bounty on this if you want to speed things up.

**Closed by korelstar** 2019-01-08 12:18 UTC
