### ISSUE TITLE
Hyphen does not turn into bullet point when pasting text after it in rich text editor.

### ISSUE THREAD

**Issue by wherop** [nextcloud/notes#1309] opened 2024-06-05 13:54 UTC
Bullet point markdown is not converted into decorated rich text, when pasting text.

## Steps to reproduce
1. type `- ` on a new line in the rich text editor (and do not type any more characters),
2. paste some text using context menu or paste keyboard shortcut

### Expected behaviour
The line should turn into a bullet list item like this (same as when the next character is typed after `- `):

- A list item

### Actual behaviour
The line remains raw text beginning with a hyphen:

`- A list item`

### Screenshots
Actual:
![incorrect](https://github.com/nextcloud/notes/assets/30728469/3f4f7f26-6dc9-4b9e-9cfc-5b91082568cd)
Expected:
![correct](https://github.com/nextcloud/notes/assets/30728469/50dab7b4-4232-40dc-b0ca-33c03110af59)

## Server
Please complete the following information.

- Notes app version: 4.10.0
- Nextcloud version: 28.0.3
- OS: Linux 5.15.0-101-generic x86_64
- Web server: Unknown
- PHP version: 8.2.18
- Database: mysql 10.5.25

**Comment by juliushaertl** [comment] 2024-06-05 14:51
Thanks for reporting, I'll close this as a duplicate of https://github.com/nextcloud/text/issues/5019 where this is already tracked

**Closed** 2024-06-05 14:52 UTC
Labels: bug, need to reproduce
