### ISSUE TITLE
No images shown in the Android Notes App - would nice if it works in the future

### ISSUE THREAD

**Issue by stefan-franz** [nextcloud/notes#1093] opened 2023-08-14 05:17 UTC
In the Android App Notes are shown no Images. Would nice if it works in the future.
Nextcloud V 27.0.2 - newest Android App on my Smartphone.

**Comment by joshtrichards** [comment] 2024-04-08 02:12
Duplicate of nextcloud/notes-android#1051

**Closed by joshtrichards** 2024-04-08 02:12 UTC
Labels: needs discussion, feature request, Android
