### ISSUE TITLE
Option to download/export a note file.

### ISSUE THREAD

**Issue by rx0a** [nextcloud/notes#1283] opened 2024-04-28 19:37 UTC
**Is your feature request related to a problem? Please describe.**
Sometimes due to using multiple devices, a device that has the older version of a note, overwrites the new changes and data loss occurs.

**Describe the solution you'd like**
As a precaution, implement a download or export dropdown menu option under the three dots for each note. Therefore, the user can download important notes, if they can't risk experiencing sync issues at a given time. It can also be handy when someone wants to just download the note and attach it to an email or transfer somewhere else, without going into nextcloud files or copy pasting it to a local text editor.
What I imagine is that under the 'preview' and 'full screen' options, there would be a 'download' button, and once clicked it would download a '.md' file of the current note to user's device.

**Describe alternatives you've considered**
I'm not sure what kind of version control or conflict resolution features exist, if any. But I've used note apps that have aggressive conflict resolutions, where you always have to go and delete the wrong versions and it becomes a hassle to the user. In nextcloud notes, it just works, except for when it doesn't and you lose something important. So instead of or in addition to reworking the conflict handling, export feature seems like a practical solution without damaging the smooth experience nextcloud notes have.

**Comment by joshtrichards** [comment] 2024-08-08 17:46
Duplicate of #766

**Closed by joshtrichards** 2024-08-08 17:46 UTC
Labels: needs discussion, feature request
