### ISSUE TITLE
Github style markdown

### ISSUE THREAD

**Issue by maxtimbo** [nextcloud/notes#446] opened 2020-02-01 03:03 UTC
**Is your feature request related to a problem? Please describe.**
I get very frustrated at the lack of markdown options available. I would love to introduce notes as an extra layer to Tx site logs, but I must have tables. 

**Describe the solution you'd like**
Tables in Markdown would be great. More features in markdown

**Describe alternatives you've considered**
n/a

**Additional context**
tables, really, just want the ability to do tables in markdown

**Comment by korelstar** [comment] 2020-02-01 06:47
Duplicate of #379

**Closed by korelstar** 2020-02-01 06:47 UTC
Labels: feature request
