### ISSUE TITLE
Syntax highlights for code

### ISSUE THREAD

**Issue by regs01** [nextcloud/notes#1017] opened 2023-04-08 15:44 UTC
It would be really nice if a code block would have a color syntax highlight.

**Comment by juliushaertl** [comment] 2023-04-14 09:16
Thanks for the feature request. I'll close this as a duplicate of the upstream tracking issue at https://github.com/nextcloud/text/issues/3618 since we use text in notes these days.

**Closed by juliushaertl** 2023-04-14 09:16 UTC
Labels: needs discussion, feature request
