### ISSUE TITLE
If the contents of the note start with a slash date the synchronization splits the note

### ISSUE THREAD

**Issue by danjde** [nextcloud/notes#242] opened 2018-08-14 16:41 UTC
Hi Staff! ;-)
I've found an issue on Cyanogenmod 12.1, no GAPS, Nextcloud 13 and Nextcloud Notes 2.4.0, Nextcloud Notes Android App 0.18.0.

If the contents of the note start with a slash date, a new addition of information in the note and its synchronization splits the note on two or three other parts, each one contains part (but not all) of the note.

Example:

```
01/02/2018 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam orci lacus, tristique id diam eu, dapibus ullamcorper velit. Sed sem libero, semper eu ipsum vel, rutrum viverra eros.

15/05/2018 Nam dictum ligula et velit cursus, ac pellentesque augue tempor. Curabitur scelerisque risus non tellus fermentum dapibus. Integer hendrerit dapibus molestie. Sed rutrum, tortor eget dapibus finibus, lorem risus bibendum elit, a laoreet ante felis non dolor.

16/05/2018, ore 1 Integer accumsan porttitor est ut volutpat. Curabitur luctus lacus eget libero mattis, at aliquet nulla blandit. Suspendisse dolor ipsum, vulputate eget nunc eget, consectetur sagittis enim. Maecenas vestibulum dui commodo, aliquet augue ullamcorper, pulvinar massa. Vestibulum commodo est massa, et accumsan lacus porttitor nec. 

29/05/2018 Praesent eget elit ultricies, pulvinar tellus quis, maximus metus. Pellentesque ultrices elit a erat consectetur, ac commodo velit faucibus. 
```
30/05/2018 correzione testo GDPR newsletter e rinnovo dominio teatroscientifico.com: ore 1

Adding data into the same note, results to splits the same note on two or thre notes with a different name, inherited from the date.

**Comment by korelstar** [comment] 2018-08-14 19:11
Sorry, I can't reproduce this issue. Can you please try to create a minimal example, where this problem occurs? Then give a step by step instruction what have to be done. Please pay attention if there is an Internet connection during these steps or not.

**Comment by danjde** [comment] 2018-08-16 08:10
If you give me an address, I can send you my original file, that contains some personal elements and I wouldn't expose here.

Thanks!

Davide

**Comment by korelstar** [comment] 2018-08-18 07:01
You can send me the file as attachment to `github`(at)`korelstar.de`.

**Comment by danjde** [comment] 2018-08-21 11:14
> This is the interesting part, since it sounds like a real bug. Please try to construct a note, where we can reproduce this. With you example data, I wasn't able to reproduce this.

Well, even I will do a file that reproduce this behavior I will send it to you.

Thanks!

**Comment by korelstar** [comment] 2018-09-25 15:50
Any news on this? I didn't receive any file since your last comment. Does the problem still occurs?

**Comment by danjde** [comment] 2018-10-11 16:37
Hi @korelstar !
The problem has recurred.
I had a text file between my notes, created in Linux (not from Notes), and with the extension "txt", named "ANNI 80.txt"(with a list of 80s music).
Editing this single file on Android by "Notes" (adding the words: "Ain't Nobody; Artist Rufus and Chaka Khan; Album Pure Urban Essentials" at the end file) 
[anni 80.zip](https://github.com/nextcloud/notes/files/2469830/anni.80.zip)
the single file has been splitted into three files: 
1) i'm only Shooting Love - Time Bandits.txt
2) JAN A P  KACZMAREK ANNI 80 .txt
3) LOVE IS LIKE OXYGEN  ANNI 80.txt

Attaching the three modified files plus the previous single one file (named "ANNI 80.txt") on "anni 80.zip"

**Comment by korelstar** [comment] 2018-10-13 18:35
The files 2. and 3. definitely didn't exist before adding the new line to "MUSICA ANNI 80.txt"? And adding the new line was definitely the only change you did?

Can you reproduce this behavior? i.e., does it always happen, when you delete the newly created files and perform the described change to "MUSICA ANNI 80.txt"?

Unfortunately, I'm still not able to reproduce this strange behavior.

**Comment by danjde** [comment] 2018-10-15 08:59
> The files 2. and 3. definitely didn't exist before adding the new line to "MUSICA ANNI 80.txt"? And adding the new line was definitely the only change you did?
> 

sure!

> Can you reproduce this behavior? i.e., does it always happen, when you delete the newly created files and perform the described change to "MUSICA ANNI 80.txt"?
> 

Yes! I've revert from Linux "MUSICA ANNI 80.txt" into Nextcloud/Notes folder, adding from Android at the file end:

_Example't example; Example Example Example; Example Example Example_ 

and obtaining the same result! Now the file is renamed and the new name is:

_i'm only Shooting Love - Time Bandits.txt_


> Unfortunately, I'm still not able to reproduce this strange behavior.

I understand, the variables involved are different!

I f you like, I can send you all my notes into a compressed file.
Also if you want I can give you an user into my Nextcloud instance for testing.


Here the file changed:
[i'm only Shooting Love - Time Bandits.txt.zip](https://github.com/nextcloud/notes/files/2478038/i.m.only.Shooting.Love.-.Time.Bandits.txt.zip)


Thanks!

Davide

**Comment by danjde** [comment] 2018-12-08 20:48
Hi @korelstar I think to have found the issue.
I had some notes/files where the first line didn't coincide with the title.
Updating these notes, "Notes" probably was looking for a match between the title and the first line, which he did not find and went to tilt! 

Ciao!

Davide

**Comment by korelstar** [comment] 2018-12-11 12:08
It's correct, that notes renames the note based on the first line. However, this should not lead to duplicating or splitting the note.

Nevertheless, if this is fixed for you, I would like to close this issue since it wasn't reproducable.

**Closed** 2019-01-06 18:58 UTC
Labels: needs info
