### ISSUE TITLE
Notes reported not compatible with update 28.0.1 (Application ver. 4.9.0)

### ISSUE THREAD

**Issue by Athar42** [nextcloud/notes#1193] opened 2023-12-26 18:26 UTC
Please make a clear and concise description of what the bug is.

==> I got the update proposal to 28.0.1 and "Notes" is reported to be "not compatible" with this release.

## Steps to reproduce
1. Install and enable this module with NC 28.0.0
2. Get the update message to NC 28.0.1
3. See the error :D 

### Expected behaviour
As the application is compatible to the 28 release, this shouldn't be triggered, so the app should be compatible (maybe a bad variable set somewhere ?)

### Actual behaviour
App is reported incompatible.

### Screenshots
![image](https://github.com/nextcloud/notes/assets/44590042/81ebeaab-d158-4b9d-b8a9-30b6ed309d46)

## Server
Please complete the following information.

- Notes app version: 4.9.0 (didn't get the update 4.9.1 on my instance)
- Nextcloud version: 28.0.0
- OS: Debian
- Web server: Apache
- PHP version: 8.3
- Database: MySQL

## Client
Please complete the following information.

- Browser (incl. version): Firefox 121
 - OS: Win 11

## Log files
Add relevant parts of your `nextcloud.log` and/or your browser's JavaScript console here.

None needed

**Comment by Artiom-M** [comment] 2023-12-27 09:09
The same with 28.0.1. It can be enabled but nothing displayed on the Notes page. At the same time Notes app seems to work.

**Comment by juliushaertl** [comment] 2023-12-27 10:08
@Athar42 I'm not sure why those versions would be marked as incompatible with 28 as both are properly listed for 28 in the app store. https://apps.nextcloud.com/apps/notes

> 4.9.0 (didn't get the update 4.9.1 on my instance)

This may be an indication that your instance hasn't fetched the latest app store data. Please check your logs for any related entries.

@Artiom-M Your error seems different, so please check if there is a better matching issue or open a new one.

**Comment by Athar42** [comment] 2023-12-27 11:08
I'm running NC 28.0.0 with Notes 4.9.0 (and is compatible with it).
But, for the upgrade to NC 28.0.1, this release is marked as "Not compatible" for some reason (just like "Two-Factor Admin Support").

For me, not on my end @juliushaertl (and I got a few app updates for other applications when I posted this bug report here and for the Two-Factor app also, so it fetch the updates when needed).

**Comment by Athar42** [comment] 2023-12-27 11:11
Oh, I see why I didn't receive the updates for those two app... they haven't been ported to support PHP8.3 yet... (while it seems to work).

Maybe that's the reason why it tells me it's not supported for NC28.0.1.

**Comment by juliushaertl** [comment] 2023-12-29 10:37
Thanks, I just released 4.9.2 which is now marked as compatible with PHP 8.3 and should become available shortly.

**Closed by juliushaertl** 2023-12-29 10:37 UTC
Labels: bug, need to reproduce

**Comment by pu15e** [comment] 2024-01-06 17:41
Got all excited about this, as notes across all my devices depends on it and they haven't worked / synced for a while... However...

This app cannot be installed because the following dependencies are not fulfilled:

    PHP with a version lower than 8.2 is required. 

This is after updating to 4.9.2.

**Comment by monperrus** [comment] 2024-03-25 20:52
Coming from #1253, I suspect the root cause is

```xml
		<php min-version="7.4" max-version="8.1" />
```

Source: https://github.com/nextcloud/notes/blob/8c48ac7ad2d91624f23c2a649a4e708691c85412/appinfo/info.xml#L25-L26

My PHP is 8.2.17.

Probably we should increase or even delete `max-version`.
