### ISSUE TITLE
Notes get deleted by CTRL+Z

### ISSUE THREAD

**Issue by DriverXX** [nextcloud/notes#308] opened 2019-05-03 17:26 UTC
If I open an existing note with a text in it and I push CTRL+Z **once** it get immediately back to the "new" state. Of course I can undo this with a CTRL+Y, but I think it is better to avoid that the first CTRL+Z delete a note.

**Comment by korelstar** [comment] 2019-05-04 19:16
I was able to reproduce this, and I think that you're right!

If anybody knows how to fix this: a pull request is very welcome :smiley:

**Comment by stefan-niedermann** [comment] 2019-05-04 19:44
Well, we could listen to the keyevent and call `preventDefault()`, but the hard part is: **when** to prevent default...

**Comment by zeroepix** [comment] 2019-12-10 03:34
A simple solution would be to have a flag that blocks ctrl-z until the file is edited. However, it then becomes a tricky problem of how to disable it again when the file is in the original condition. If it's possible to keep track of "edits" discretely, you could have a counter which increments for each edit event. When a ctrl-z happens, this counter is decremented until it hits 0 again, and ctrl-z is again disabled. I don't know how feasible this is, but it does look like the browser has some sort of timer to know how far to undo, rather than actual characters. 

If you can figure out that part, disabling ctrl-z could be done like this:

```
// editCounter is defined and updated elsewhere

var ctrlDown = false;
var zKey = 90;

// track ctrl being pressed
$('body').keydown(function(e) {
  if (e.keyCode == 17 || e.keyCode == 91) {
    ctrlDown = true;
  }
}).keyup(function(e) {
  if (e.keyCode == 17 || e.keyCode == 91) {
    ctrlDown = false;
  }
});

// then block when the counter is 0
$("body").keydown(function(e) {
  if ((ctrlDown && e.keyCode == zKey) && (editCounter <= 0)) {
    e.preventDefault();
    return false;
  }
});
```

**Comment by Boki4d** [comment] 2020-03-19 21:19
Had the same issue today and wanted to open an issue here, but then I found this issue.
"Funny" thing is, that I worked on an older and rather big note and made some changes within the text. While I was trying to Change the headline I accidentally hit **Ctrl-Z** and the whole text was gone, not only the last part I changed. I immediately tried to get it back with **Ctrl-Y*, but it was gone, no chance to restore it.
I get that it is hard to distinguish between an intentional Keyboard-Event and a unintentional one, but what about a version history for every note? 5 Version per note. I think that would be enough to retain this behaviour.

**Comment by korelstar** [comment] 2020-03-27 07:54
@Boki4d Nextcloud already saves a version history by default. You can restore old versions using the files app.

It looks that the Nextcloud Text app doesn't have this problem. So this issue will be fixed after implementing #331.

**Comment by Boki4d** [comment] 2020-03-27 11:40
@korelstar 
I guess you're right that the editor of the Text App might fix the issues in the future. But I still suggest to make the version history accessible from the Notes App without having to switch to the Files App.

**Comment by korelstar** [comment] 2020-03-27 13:32
I agree. We have already an issue for this: #144 ;-)
I hope, the implementation will be easier with #331, because the text app also shows the version history in it's sidebar.

**Closed** 2022-02-27 18:54 UTC
Labels: bug, help wanted, feature: EasyMDE
