### ISSUE TITLE
Add syntax highlighting for code blocks

### ISSUE THREAD

**Issue by mat-m** [nextcloud/notes#1022] opened 2023-04-16 23:51 UTC
**Is your feature request related to a problem? Please describe.**
As a SRE, I stored many information with snippets of code.
Language varies depending on operations & apps, so I would appreciate Syntax highlighting to ease reading the code

**Describe the solution you'd like**
Using standard syntax triple-backquote  followed by language name, you get syntax highlighting in Preview, like on Github/gitlab readmes (https://github.com/ohmyzsh/ohmyzsh)

**Describe alternatives you've considered**
Getting back to Notion...

**Comment by juliushaertl** [comment] 2023-04-24 13:56
Thanks for the suggestion, I'll close this as a duplicate of https://github.com/nextcloud/notes/issues/1017 with https://github.com/nextcloud/text/issues/3618 being the actual text editor issue to track this further.

**Closed by juliushaertl** 2023-04-24 13:56 UTC
Labels: needs discussion, feature request
