### ISSUE TITLE
Option to hide headings please.

### ISSUE THREAD

**Issue by DarkRookie00** [nextcloud/notes#784] opened 2021-11-26 16:56 UTC
**Is your feature request related to a problem? Please describe.**
I do not like the headings for the groupings when opening the app.

**Describe the solution you'd like**
Either an option to disable the grouping, or a setting to select a default folder as the folders do not seem to have this issue.

**Describe alternatives you've considered**
I use QOwnNotes to get around this on the desktop, but that isn't always an option.

**Additional context**
![image](https://user-images.githubusercontent.com/56938431/143612360-51e96283-7ac5-41de-8b11-e7e4a5a93d95.png)

**Comment by korelstar** [comment] 2021-12-02 20:00
Duplicate of #521

**Closed by korelstar** 2021-12-02 20:00 UTC
Labels: needs discussion, feature request
