### ISSUE TITLE
Checklist with reverse formatting

### ISSUE THREAD

**Issue by talesam** [nextcloud/notes#728] opened 2021-06-15 02:35 UTC
Version Nextcloud: **21.0.2**
Version Notes: **4.0.4**

I went to create a checklist formation and verified that the formatting is wrong in the editing part and in the visualization parts.

The check list was created as follows:
`- [ ]`
`- [x]`

**Edit mode**
![photo_2021-06-14_23-32-29](https://user-images.githubusercontent.com/981368/121984220-fb385d00-cd68-11eb-9ec7-33d486806ce5.jpg)

**View mode**
![photo_2021-06-14_23-33-11](https://user-images.githubusercontent.com/981368/121984251-0be8d300-cd69-11eb-8917-a0e083b9deed.jpg)

**Comment by korelstar** [comment] 2021-06-15 03:14
> the formatting is wrong in the editing part

What exactly is wrong here?

Regarding the view mode, this is already documented in #325

**Comment by talesam** [comment] 2021-06-15 03:55
> > a formatação está errada na parte de edição
> 
> O que exatamente está errado aqui?
> 
> Quanto ao modo de visualização, isso já está documentado em [# 325](https://github.com/nextcloud/notes/issues/325)

Hey, just look at the image, the boxes with the line appear in edit mode, and in preview mode it shows square brackets, it was supposed to be inverted.

See: https://github.blog/2014-04-28-task-lists-in-all-markdown-documents/
This link shows the edit mode before and preview after, see the difference.

**Comment by korelstar** [comment] 2021-06-15 05:52
Preview mode still misses rendered checkboxes, yes. But as I wrote, there is already an issue for this: #325.

Edit mode in this app is different to edit mode in your link. The notes app's edit mode provides markdown formatting wherever possible. So it's a feature and not a bug that check boxes are rendered here.

**Comment by korelstar** [comment] 2021-06-15 05:52
Duplicate of #325

**Closed by korelstar** 2021-06-15 05:52 UTC
Labels: bug, need to reproduce
