### ISSUE TITLE
The app doesn't work with E2EE

### ISSUE THREAD

**Issue by marmistrz** [nextcloud/notes#344] opened 2019-07-18 16:08 UTC
**Describe the bug**
Notes can be accessed and modified, even if the `Notes` folder is encrypted

**To Reproduce**
1. Enable E2EE on the Android app
2. Create a note using the Android app
3. Open the notes using the web client

**Expected behavior**
Due to encryption, the notes should not be available

**Actual behavior**
The notes are freely available from the notes app.

**Server (please complete the following information):**
- Notes app version: unknown
- Nextcloud version: 16.0.3
- OS: unknown
- Web server: cloud.allsync.com
- PHP version: unknown
- Database: unknown

**Client (please complete the following information):**
Firefox 68 @ Arch Linux / Android App v0.24.3

**Log files**
N/A

**Comment by korelstar** [comment] 2019-07-18 19:36
What do you mean with "Android app"?
Due to the version "v0.24.3" I think you mean the app [Nextcloud Notes](https://github.com/stefan-niedermann/nextcloud-notes). However, that app has no option to "Enable E2EE". Hence, please provide more details about the used app and which (detailed) steps have to be executed in order to reproduce this issue.

**Comment by marmistrz** [comment] 2019-07-18 19:41
@korelstar Yes, that's what I mean. Then the app should show an error if the Notes folder is encrypted. Otherwise, users using E2EE with Nextcloud may think their notes are secure.

**Comment by korelstar** [comment] 2019-07-18 19:45
I still don't get what do you mean by "Enable E2EE on the Android app" if that app hasn't this feature.

Again: please provide more details about the used app and which (detailed) steps have to be executed in order to reproduce this issue.

**Comment by korelstar** [comment] 2019-09-17 14:55
Closing due to missing feedback.

**Closed by korelstar** 2019-09-17 14:55 UTC
Labels: needs info
