### ISSUE TITLE
Notes not loading after update to 4.1.0

### ISSUE THREAD

**Issue by drikqlis** [nextcloud/notes#732] opened 2021-06-28 08:06 UTC
Please make a clear and concise description of what the bug is. Please note, that issues with the Android app have to be reported under https://github.com/stefan-niedermann/nextcloud-notes/issues and issues with Nextcloud's Text app have to be reported under https://github.com/nextcloud/text/issues .

## Steps to reproduce
1. Update to 4.1.0
2. Notes not loading at all.

### Expected behaviour
Notes should load.

### Actual behaviour
Notes not loading, error "Could not load notes, check JavaScript console and server log."
JavaScript console:
```
TypeError: t is undefined
    a notes-main.js:2
    updateNotes notes.js:126
    v vuex.esm.js:741
    dispatch vuex.esm.js:505
    dispatch vuex.esm.js:397
    fetchNotes NotesService.js:78
NotesService.js:93:12
```
Server logs (don't know if it is connected):
```
  | Error: session_start():  Ignoring session_start() because a session is already active at  /var/www/html/nextcloud/lib/private/Session/Internal.php#207<<closure>>OC\Log\ErrorHandler::onError()<<closure>>session_start()/var/www/html/nextcloud/lib/private/Session/Internal.php - line 207: call_user_func_array()/var/www/html/nextcloud/lib/private/Session/Internal.php - line 217: OC\Session\Internal->invoke()/var/www/html/nextcloud/lib/private/Session/Internal.php - line 107: OC\Session\Internal->startSession()/var/www/html/nextcloud/lib/private/Session/CryptoSessionData.php - line 150: OC\Session\Internal->clear()/var/www/html/nextcloud/lib/private/User/Session.php - line 932: OC\Session\CryptoSessionData->clear()/var/www/html/nextcloud/lib/private/AppFramework/Middleware/Security/CORSMiddleware.php - line 91: OC\User\Session->logout()/var/www/html/nextcloud/lib/private/AppFramework/Middleware/MiddlewareDispatcher.php - line 98: OC\AppFramework\Middleware\Security\CORSMiddleware->beforeController()/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 119: OC\AppFramework\Middleware\MiddlewareDispatcher->beforeController()/var/www/html/nextcloud/lib/private/AppFramework/App.php - line 157: OC\AppFramework\Http\Dispatcher->dispatch()/var/www/html/nextcloud/lib/private/Route/Router.php - line 302: OC\AppFramework\App::main()/var/www/html/nextcloud/lib/base.php - line 993: OC\Route\Router->match()/var/www/html/nextcloud/index.php - line 37: OC::handleRequest()
-- | --
```

## Server
Please complete the following information.

- Notes app version: 4.1.0
- Nextcloud version: 21.0.2
- OS: Ubuntu 18.04.02 LTS
- Web server: Apache2
- PHP version: 8.0
- Database: MariaDB

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

## Client
Please complete the following information.

- Browser (incl. version): Firefox
 - OS: Arch Linux

## Log files
Add relevant parts of your `nextcloud.log` and/or your browser's JavaScript console here.

**Comment by lllvvv** [comment] 2021-06-28 16:31
Yes, I can reproduce this. I lost access to Notes on the web interface after updating to 4.1.0, but I can still access it via the Android App. I'll have a look at the console/dev tools later. My config is similar to the OP's, the only difference is that I'm using Nginx and Postgresql instead.

**Comment by korelstar** [comment] 2021-06-28 20:31
I can't reproduce this, but I'm still analyzing.

@drikqlis : is the exact wording of the error message really "Could not load notes, check JavaScript console and server log."? I can't find such a message in the code. Could you please check again and post the exact wording?

Please also try to restart your web server and php-fpm. In the past, we've often seen caching problems after updating.

**Comment by drikqlis** [comment] 2021-06-28 22:45
That's a rough translation, my Nextcloud is in Polish. Exact message in Polish:
"Pobranie notatek nie powiodło się. Szczegółowe informacje można znaleźć w konsoli JavaScript i w dzienniku serwera."
Restart helped and I can now see the notes so looks like it was some cashing issue, thanks.

**Comment by lllvvv** [comment] 2021-06-29 09:27
In my case, restarting php-fpm, or even the whole server, still leads to this bug.

Eventually I figured out what was happening. For some reason, the permission of the files for the notes app got changed from 775 to 770. This is problematic due to the fact that php-fpm pool is running under a different user than the nginx server (which is now the standard for webapps in Arch). Don't know if this was introduced by the update, but I followed the normal procedure for updating apps (occ app:update --all) and this is the first time something breaks like this.

**Comment by RlndVt** [comment] 2021-07-08 08:15
I'm having the same issue, from browser log when attempting to view notes:

```
The resource from “https://nextcloud.XXX.yy/index.php/apps/dashboard/” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff). notes
```

**Comment by korelstar** [comment] 2021-07-13 16:35
@lllvvv

Interesting, but this is indeed unrelated to the notes app. The files in the release package have 755 resp. 644 permissions:
```
$ tar tvf notes.tar.gz
drwxr-xr-x runner/docker     0 2021-06-27 15:33 notes/
drwxr-xr-x runner/docker     0 2021-06-27 15:31 notes/img/
-rw-r--r-- runner/docker   531 2021-06-27 15:31 notes/img/favicon-touch.svg
-rw-r--r-- runner/docker   693 2021-06-27 15:31 notes/img/recent.svg
...
```

But I'm wondering if you can easily fix your issue by adding the nginx user to the php-fpm group or the other way around.

@RlndVt
It doesn't look like your issue is the same as the others have. Please create a new issue using the issue template. I need more information for digging into this. But please check first, if a server restart helps you, too.

-----

Summary:
- Issue by @drikqlis was fixed by restarting the server.
- Issue by @lllvvv is unrelated to the notes app.
- Issue by @RlndVt will be continued in a new ticket.

Hence, I'm closing this issue because I don't want to mixup more problems in this single ticket.

**Closed by korelstar** 2021-07-13 16:35 UTC
Labels: bug, need to reproduce
