### ISSUE TITLE
Special characters not work

### ISSUE THREAD

**Issue by cayetano** [nextcloud/notes#93] opened 2017-05-23 21:25 UTC
Latin characters like á é í ó ú ñ etc... not work

Regards
Cayetano

**Comment by korelstar** [comment] 2017-05-24 04:37
Which version do you use? There is a bug fix in the area of charter encoding which isn't released yet. But you can test it if you use the master branch of this Git repository.

If the problem still occurs, please give more details what exactly doesn't work.

**Comment by notklaatu** [comment] 2017-07-14 05:18
Titling a note this:
``Pączki``
causes the notes app to hang. The note text file in $USER/Notes is labelled ``P``.

**Comment by notklaatu** [comment] 2017-07-14 11:29
nextCloud-clients can no longer sync, citing missing file ``P``. Disabling Notes, moving Note files to a local machine, deleting Notes from server, re-enabling notes, and then copying old notes back to server appears to fix the problem.

**Comment by korelstar** [comment] 2017-07-30 09:22
Ouh, I can confirm this bug. This is really uncomfortable, since it's really hard to delete the file with the bad character.

This definitely has to be fixed.

**Comment by korelstar** [comment] 2017-08-20 15:09
This should be fixed, now (in `master`). Please see #125.

**Closed by korelstar** 2017-08-20 15:09 UTC
Labels: bug
