### ISSUE TITLE
Fulltext Search

### ISSUE THREAD

**Issue by fajabird** [nextcloud/notes#496] opened 2020-04-24 07:03 UTC
I was not able to find any information if this should already work or there are currently any issues (on my side or in general), but I cannot search for content of my notes. Nextcloud default search (CTRL-F) will only search in file-names of the notes files. For e.g. the deck-app there is a fulltestsearch-provider listed but non for notes.

**Comment by korelstar** [comment] 2020-04-24 18:13
Duplicate of #288

**Closed by korelstar** 2020-04-24 18:13 UTC
Labels: feature request
