### ISSUE TITLE
Always creating notes, endless.

### ISSUE THREAD

**Issue by binarykitchen** [nextcloud/notes#979] opened 2023-03-07 08:03 UTC
![2023-03-07_19-36](https://user-images.githubusercontent.com/177641/223360791-49b62b10-b0f4-4db6-8d1e-f5163b1e7c3f.png)
Screenshot says it all. Will collect all the other information now and put them below.

**Comment by binarykitchen** [comment] 2023-03-07 08:03
Nextcloud

```
Nextcloud Hub II (23.0.10)
````

Server

```
Operating System:	Linux 5.15.0-1031-aws x86_64
CPU:	Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz (1 core)
Memory:	966.00 MB
Server time:	Tue Mar 7 19:39:53 NZDT 2023
```

PHP

```
Version: 8.0.28
Memory Limit: 512 MB
Max Execution Time: 3600
Upload max size: 16 GB
```

DB

```
Type: sqlite3
Version: 3.37.2
Size: 215.2 MB
```

**Comment by binarykitchen** [comment] 2023-03-07 08:03
Initially reported in https://github.com/owncloud/notes/issues/441 :(

**Comment by binarykitchen** [comment] 2023-03-22 20:24
Yeah, that's why I've created this PR:
https://github.com/mail-in-a-box/mailinabox/issues/2243

Sorry, I do not have more information to reproduce this.

**Comment by JonnyTischbein** [comment] 2023-03-22 20:43
Following the release schedule I would recommend to upgrade to at least 24.0.10

**Comment by joshtrichards** [comment] 2024-08-08 18:18
Not much we can do here without logs. Check web server logs to see where transactions are coming from, etc. 

Hopefully you got this addressed in the meantime. Not sure what you encountered - never seen this.

If still happening I'd encouraging trying to isolate the cause via the community help forum - https://help.nextcloud.com. If that leads to a likely bug, let us know here. 

Closing since there haven't been further similar reports and this isn't actionable as it stands.

**Closed by joshtrichards** 2024-08-08 18:18 UTC
Labels: bug, need to reproduce
