### ISSUE TITLE
App-Error: Request failed: unacceptable content-type: text/html

### ISSUE THREAD

**Issue by Qixuga** [nextcloud/notes#147] opened 2017-11-04 07:05 UTC
May be its a but on the API/Server-Site but my Cloundnotes shows always after synchronisation the errormessage of inacceptable content type:

Request failed: unacceptable content-type: text/html

May be i try to overwrite the content typ via htaccess ;-)
Or directly to php-code if i know the suggested one:
`header('Content-type: application/json');`

can you fix it?
thank you very much for your great work!

ps: ups - i knew this wasn't the app repo...

**Comment by korelstar** [comment] 2017-11-04 16:38
I don't think that's the source of your problem. The app sends the correct content-type header. However, the server sends `text/html` if an unhandled exception happened on the server. Therefore, please check your server's `nextcloud.log` for related log entries and post an excerpt of them, here.

**Comment by jancborchardt** [comment] 2018-06-04 23:47
Closing because the issue is quite old. If it still happens, feel free to open another issue with the contents of your nextcloud.log. :)

**Closed by jancborchardt** 2018-06-04 23:47 UTC
Labels: bug

**Comment by Qixuga** [comment] 2018-08-21 15:00
OK, thank you!
