### ISSUE TITLE
Categories to organize notes

### ISSUE THREAD

**Issue by Larsene** [nextcloud/notes#159] opened 2017-12-30 22:36 UTC
Please, could you provide categories editor to organize notes ?

Many Thanks for your work !

**Comment by 1337sup3rh4x0r** [comment] 2018-01-02 15:39
#8

**Comment by korelstar** [comment] 2018-04-04 19:24
Duplicate of #8

**Closed by korelstar** 2018-04-04 19:24 UTC
Labels: duplicate

**Comment by jouhoff** [comment] 2018-10-31 08:12
No one?
