### ISSUE TITLE
Appearance of Checkboxes mixed up

### ISSUE THREAD

**Issue by mucke5** [nextcloud/notes#619] opened 2020-10-01 13:59 UTC
The appearance of the checkboxes is swapped, in edit mode is the icon and in preview mode is the formatting indicator.

![image](https://user-images.githubusercontent.com/13103826/94818973-01ff8980-03ff-11eb-89b8-8b1fc2580725.png)

**Comment by stefan-niedermann** [comment] 2020-10-01 14:21
Dear @mucke5 

first of all: this repository is only about the server app, the one for the android app is here: https://github.com/stefan-niedermann/nextcloud-notes/issues/new?labels=bug&template=bug_report.md

Secondly, yes, this is a known limitation of the currently used markdown editor, which is not capable of handling "nice" checkboxes in the edit mode. As soon as we find a solution, we will implement it, of course 🙂

**Comment by korelstar** [comment] 2020-10-01 18:42
Duplicate of #325

**Closed by korelstar** 2020-10-01 18:42 UTC
