### ISSUE TITLE
Ctrl-Z is deleting notes

### ISSUE THREAD

**Issue by petitminion** [nextcloud/notes#435] opened 2020-01-14 09:51 UTC
When I use Crtl-Z shortcut, all content of the note I'm writing in is deleted. I would expect this shortcut to just delete the last word or sentence...I lost various notes that way, because they cannot be found in the trash..

**Comment by stefan-niedermann** [comment] 2020-01-14 10:28
Duplicate of https://github.com/nextcloud/notes/issues/308

Let's continue the discussion there.

**Closed by stefan-niedermann** 2020-01-14 10:28 UTC
Labels: duplicate
