### ISSUE TITLE
Save when switching notes

### ISSUE THREAD

**Issue by BloodyIron** [nextcloud/notes#300] opened 2019-03-11 02:16 UTC
I'm a fast typer, so I can often switch from one note to another fast. Sometimes when I make adjustment to a note in the webGUI, then switch to another node, the changes I just made don't save.

Can we get it so when you switch to another note it immediately saves the previous note changes please?

Sometimes saving doesn't quite work 100% on android either, but not sure if that's the same issue or not.

Thanks! :D

**Comment by korelstar** [comment] 2019-03-13 07:07
I can't reproduce this issue: even if I switch to another note before the last note was saved (I still see the star behind the note's title in the app navigation), the last note is saved some seconds later.

Could you please describe the exact steps to reproduce this? Please give also some hints about your environment (e.g. speed of your internet connection, the server and the client; browser version, operating system, Nextcloud version, Notes version, etc.).

The Android problem should be discussed in a separate issue in the Android app's repository.

**Comment by BloodyIron** [comment] 2019-03-15 15:58
This is on LAN through a reverse proxy, browser is Vivaldi, Ubuntu 18.10, NC 15.0.1, Notes version 2.5.1

Steps are identical as described above.

**Comment by korelstar** [comment] 2019-03-16 12:55
Please try if this also happens in (e.g.) Firefox.

**Comment by BloodyIron** [comment] 2019-03-16 16:46
It happens occasionally in Firefox. But it is not easy to reproduce, namely because I have to type and switch really fast to reproduce it. Something I do legitimately do from time to time. And it took multiple consecutive attempts to get it to happen again. (this is firefox btw, same behaviour as observed in Vivaldi).

Firefox 65.0.1 64-bit Ubuntu

**Comment by iSpeeX** [comment] 2019-04-15 10:17
I don't know if I have the same case as you, but I can tell that's it's diffucult to me to see when a note is saved and it seems to be pretty slow.
Can you add a "save" button or "synchronize" button ?

**Comment by korelstar** [comment] 2019-04-15 13:02
@iSpeeX You can press CTRL+S in order to manually save the current note.

**Comment by iSpeeX** [comment] 2019-04-15 13:14
Oh crap... I tried to use this "standard" shortcut, but everytime i use it, i get a pop-up to save the entire page in HTML.
Maybe it's due to opera (my browser), will try later ! Thank you very much

**Comment by BloodyIron** [comment] 2019-04-15 15:00
FYI sometimes when I hit ctrl+s my browser things I want to save the page, then brings up my OS "save as" kind of interface. But sometimes it properly triggers the notes save tooo.

The issue I was having isn't frequent, but I think it might be from rapid switching between notes that are saving, or trying to save.

**Comment by korelstar** [comment] 2019-06-15 06:01
@BloodyIron I've just released v3.0.0 which contains a complete rewrite of the JavaScript part. Please test again with this version and give some feedback.

**Comment by BloodyIron** [comment] 2019-06-15 15:32
@korelstar okay! :)

**Comment by korelstar** [comment] 2019-08-20 18:30
Any news on this? Did the issue occur again?

**Comment by BloodyIron** [comment] 2019-08-21 00:48
At this point, I haven't observed the issue resurface. Thanks for the help! :D

**Comment by xxKeith20xx** [comment] 2019-08-21 00:50
I've seen this occur in the past and just make sure to not leave a notes page open if I remember to. I think that causes some syncing quirks depending on how many devices it's open in?

**Comment by BloodyIron** [comment] 2019-08-21 00:51
Have you tried since the new release? Have you re-tested with that version? I have and for me, it doesn't happen.

if you could retest with the latest version, and reproduce the issue, I bet that'd be helpful to the dev.

> I've seen this occur in the past and just make sure to not leave a notes page open if I remember to. I think that causes some syncing quirks depending on how many devices it's open in?

**Comment by xxKeith20xx** [comment] 2019-09-01 18:00
@BloodyIron I haven't had any issues whatsoever on the latest version of Notes and Nextcloud 16.0.4

**Comment by korelstar** [comment] 2019-09-01 19:11
Great! Then, I'll close this issue. Thanks for your feedback :-)

**Closed by korelstar** 2019-09-01 19:11 UTC
Labels: feature: editor, needs info
