### ISSUE TITLE
Zero Width Joiner (U+200D) character not working properly

### ISSUE THREAD

**Issue by shajilkrazy** [nextcloud/notes#302] opened 2019-03-29 11:36 UTC
When using the **web interface** for note editing, special characters like **Zero Width Joiner** (U+200D) and **Zero Width Non Joiner** (U+200C) are displayed as red dots. I needed proper rendering of these special characters as many of the Indic languages use these characters for generating some variants of letters. Thus, some of the texts in indic languages (e.g.: Malayalam) are shown improperly. However these perfectly work in my android device with NextCloud Notes app.
This image shows how it is displayed in the web browser: ![zwj](https://user-images.githubusercontent.com/36438487/55229927-52af8880-5244-11e9-87ac-d519e4ff516a.png)
and this is how the text should be: ![zwj2](https://user-images.githubusercontent.com/36438487/55229935-5a6f2d00-5244-11e9-8227-67bf1ad50c52.png)
So, I wish to know whether this problem is solvable.

**Comment by korelstar** [comment] 2019-03-31 12:47
Which version of Nextcloud and of the notes app do you use?

Could you please post the original character sequence, here, if possible? Then we can experiment with it easier (copy & paste).

**Comment by shajilkrazy** [comment] 2019-04-02 15:10
I am using Nextcloud under the provider [CloudFiles ](https://files.kmu.cnow.at). I access NextCloud in web browser via: "https://files.kmu.cnow.at"
I doubt whether the problem is of my provider.
The version of Notes app in Android is 0.24.3
The original character sequence as requested by you: ര്‍ ന്‍ ല്‍.
If you don't have a font supporting these characters, you may download [Noto Serif Malayalam](https://noto-website-2.storage.googleapis.com/pkgs/NotoSerifMalayalam-hinted.zip)

**Comment by korelstar** [comment] 2019-04-03 17:51
I can confirm this bug. Maybe we can fix this, when we switch to another editor (see #204).

**Comment by shajilkrazy** [comment] 2019-04-03 18:03
Okay. Thank you!

**Comment by korelstar** [comment] 2022-10-01 19:55
Just tested again and this issue seems to be fixed in the meanwhile. :smiley:

**Closed by korelstar** 2022-10-01 19:55 UTC
Labels: bug, help wanted, feature: EasyMDE
