### ISSUE TITLE
Internal server error from non-utf8 file

### ISSUE THREAD

**Issue by nanaya** [nextcloud/notes#73] opened 2017-03-28 12:07 UTC
### Steps to reproduce
1. Store this [test file (shift-jis)](https://cloud.myconan.net/s/vOK2X3czRpUCdzN/download) to notes directory
2. Open note

### Expected behaviour
Directory listing

### Actual behaviour
No directory listing (error 503)

### Server configuration
**Operating system**: FreeBSD 11.0

**Web server:** nginx 1.10.3

**Database:** postgresql 9.6

**PHP version:** 7.1.3

**Nextcloud version:** 11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** internet

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

redacted because of too long. I hope my test file is enough and that it's not my configuration mistake. Otherwise I'll come back and fill up everything.

**Comment by nanaya** [comment] 2017-03-28 12:10
Note that I'm not expecting some magic file encoding detection, just that it shouldn't completely fail when encountering such file.

**Comment by korelstar** [comment] 2017-03-31 06:08
Thanks for reporting this bug and for providing the test file. I can reproduce the bug and agree that this should be fixed.

**Comment by korelstar** [comment] 2017-03-31 19:51
I think the problem is, that `json_encode()` returns `false` (and maybe other functions don't work correctly, too) for such invalid strings. This can be tested using `mb_check_encoding($string, 'UTF-8')`. However, I'm not sure what's the desired behavior after the invalidity was detected.
- remove invalid characters? if you edit the note, the file is saved without the characters (easiest fix).
- provide a warning and open the note read-only? that needs many changes in the implementation.
- ... ?

**Comment by nanaya** [comment] 2017-03-31 20:00
hide the file at all?

**Comment by korelstar** [comment] 2017-03-31 20:08
Hmm. Hiding would hinder us from not showing at the content when we only load the list of notes. So that's not a good idea. But why do you have such a file in your notes directory?

**Comment by nanaya** [comment] 2017-03-31 20:09
I was migrating my old notes (a bunch of txt files) and not all of them are in utf8.

**Comment by korelstar** [comment] 2017-03-31 20:11
What encoding do they use? Maybe we can try to transcode such files automatically (e.g. using `mb_detect_encoding(...)`) ...

**Comment by nanaya** [comment] 2017-03-31 20:13
Iirc the non-utf8 files were shift-jis and utf-16.

**Comment by korelstar** [comment] 2017-04-01 06:18
@Henni @jancborchardt
What do you think about an automatically encoding conversion to utf-8 using `mb_convert_encoding()`? Then, those special files (with other encoding) don't break the app. However, if you edit a file using the note app, the file will be saved in utf-8.

**Comment by Henni** [comment] 2017-04-10 17:00
@korelstar I don't really have that much experience with file encoding. But if you think this would solve this problem, I'd love to see a PR. :wink:

**Comment by korelstar** [comment] 2017-04-10 19:07
@Henni Great to see you again, here!

`mb_detect_encoding` didn't work as expected, so I did a simple fix for this in #80.

**Closed** 2017-04-10 20:11 UTC
Labels: bug
