### ISSUE TITLE
Allow to manually save notes

### ISSUE THREAD

**Issue by KopfKrieg** [nextcloud/notes#113] opened 2017-07-15 15:31 UTC
Currently, and in reference to all the other issues related to saving notes and losing notes, I propose the idea to implement a manual save method, either via a button or Ctrl+S, including a message showing "Note saved" (or, if it failed, an appropriate error message).

Any ideas on this? Could that be implemented?

**Comment by louis-eyond** [comment] 2017-08-17 19:27
This is very needed, as I'm worried about losing content all the time (due to the various issues around locked files and auto-save).  Additionally, a "Last Saved" time indicator while the note is open would  alleviate some of this worry.

**Comment by korelstar** [comment] 2017-08-31 17:45
I think, the most important enhancement would be to show a warning, if saving was not successful, regardless of whether the trigger was auto-save or a to be implemented manual save. The message could be supplemented with a button "try again". Wouldn't that be sufficient?

On the other hand, showing the last saved time can also be helpful. But this would be another information that can distract from writing.

/cc @nextcloud/designers

**Comment by jancborchardt** [comment] 2017-09-01 10:14
We should simply hijack Ctrl-S to manually save the note. We do the same in the texteditor app in files.

cc @Henni @korelstar

**Comment by Espina2** [comment] 2017-09-01 12:42
Or cmd + s on a Mac. :)

**Comment by korelstar** [comment] 2017-09-02 08:58
I'm fine with that (see also #120, which is kind of a duplicate of this).

But we should definitely (also) show an error message, if saving failed.

**Closed** 2017-11-13 12:12 UTC
