### ISSUE TITLE
Share notes and possibly even whole categories

### ISSUE THREAD

**Issue by user13v31** [nextcloud/notes#647] opened 2020-12-14 21:26 UTC
I think it would be helpful to be able to share and co-edit notes and possibly even notes of a specific category with others. For example if used in a working environment (todo-lists, etc) or in a family (shopping lists, plans)...
atm the 'workaround' is to share single files, but it's kind of unhandy especially if i want to share more notes or if the notes change (different shopping lists, a new one every week). Hence the proposal to add a special "shared with"-Category, to be able to define different categories that will be shared with different people.

**Comment by stefan-niedermann** [comment] 2020-12-14 21:29
Partially duplicate of https://github.com/nextcloud/notes/issues/38

**Comment by korelstar** [comment] 2020-12-22 14:24
Duplicate of #285

**Comment by korelstar** [comment] 2020-12-22 14:25
Please see https://github.com/nextcloud/notes/issues/285#issuecomment-448686822 for a workaround.

**Closed by korelstar** 2020-12-22 14:24 UTC
