### ISSUE TITLE
Some text formatting improvements

### ISSUE THREAD

**Issue by tiaga** [nextcloud/notes#175] opened 2018-03-10 09:51 UTC
Hello,

I want to suggest some improvements for text formatting:
1. To be able to change strings width (at the moment string width is 87 symbols and it looks strange on Full HD display). For example it can be adjusted to screen width.
2. Apply text formatting only if a closing tag exists.
3. If code formatting (```) is using, highlight all code area. As an example:
![notes](https://user-images.githubusercontent.com/10153548/37240624-af4ad966-2480-11e8-92be-c8ba3b648a4b.png)

**Comment by jancborchardt** [comment] 2018-06-04 23:03
@tiaga could you create separate issues for these 3 separate issues? 1. for example is a duplicate of https://github.com/nextcloud/notes/issues/182

Thanks! :)

**Closed by jancborchardt** 2018-06-04 23:03 UTC
Labels: enhancement, good first issue
