### ISSUE TITLE
Notes keep scrolling up

### ISSUE THREAD

**Issue by RTechSn** [nextcloud/notes#1227] opened 2024-02-04 11:28 UTC
Hello. 
The last update brought a major inconvenience when working with Notes via a web browser.

## Steps to reproduce
1. Open a note
2. Scroll down to a part you are working with
3. Switch to another tab\window

### Expected behaviour
Your position in the document should remain

### Actual behaviour
The note is scrolled to the beginning

## Server
Please complete the following information.

- Notes app version: 4.9.2
- Nextcloud version: Nextcloud Hub 7 (28.0.2)
- OS: Ubuntu 22.04
- Web server: Firefox 122.0
- PHP version: 8.1-FPM
- Database: PostgreSQL

**Comment by bonswouar** [comment] 2024-02-07 16:31
I can confirm the issue is also present on Chrome 121.0.6167.140
And it also happens if you save the note manually (clicking on the check-mark)

This makes the notes webapp on desktop almost totally unusable, any workaround?
_Meanwhile I might give a chance to qownnotes (I wish there was an official native desktop app though!)_

**Comment by poiNt3D** [comment] 2024-02-07 20:16
This may be related to the problem with Files web-app, the page is scrolling to the top after bringing up the right-click menu.

**Comment by MrRinkana** [comment] 2024-02-19 11:43
For me this happens even when clicking any of the menu options in the top row, like header, warning, save etc. Some examples of behaviour:

- Text styling options: the view jumps/flickers up then back down, but not to the exact same location
- Adding link: first jumos up, and then back down when you finish adding the link (click the arrow)
- Adding or removing headers, sections (warn, info etc.) just jumps up
- Saving just jumps up

The "scroll" is more of a jump (it is instant)
I am using the rich-text editor.

It only happens while in the notes app (what I found); if I open the same file in the same rich-text editor from Files it does not scroll up. The difference seems to be that in the files app rich-text opens in "full screen" with the cross to close.

This makes editing notes in the notes app very disorienting, and working on longer files more or less impossible.

**Comment by bufferlow** [comment] 2024-02-19 19:22
I have the same issue - killing my workflow :-( 

Notes app version: 4.9.2
Nextcloud version: Nextcloud Hub 7 (28.0.2)

**Maybe I found a workaround**: Opening notes via file browser provides almost the same editor view and same functions the notes app does. But it work without the scroll-jump issue.

**Comment by arnowelzel** [comment] 2024-02-25 02:16
> For me this happens even when clicking any of the menu options in the top row, like header, warning, save etc. Some examples of behaviour:
> 
> * Text styling options: the view jumps/flickers up then back down, but not to the exact same location
> * Adding link: first jumps up, and then back down when you finish adding the link (click the arrow)
> * Adding or removing headers, sections (warn, info etc.) just jumps up
> * Saving just jumps up
> 
> The "scroll" is more of a jump (it is instant) I am using the rich-text editor.
> 
> It only happens while in the notes app (what I found); if I open the same file in the same rich-text editor from Files it does not scroll up. The difference seems to be that in the files app rich-text opens in "full screen" with the cross to close.
> 
> This makes editing notes in the notes app very disorienting, and working on longer files more or less impossible.
> 
> I'm on nc 28.0.2 and notes 4.9.2

I can confirm this behaviour. Howevet, this does not happen in Collectives or the text editor - so it seems to be a specific issue with Notes and not the editor component.

**Comment by McLibboc** [comment] 2024-02-27 11:47
Same issue here when using the rich text editor for notes.

**Comment by Finn10111** [comment] 2024-02-28 21:23
> I have the same issue - killing my workflow :-(
> 
> Notes app version: 4.9.2 Nextcloud version: Nextcloud Hub 7 (28.0.2)
> 
> **Maybe I found a workaround**: Opening notes via file browser provides almost the same editor view and same functions the notes app does. But it work without the scroll-jump issue.

Thank you for sharing your workaround - works for me!

**Comment by beardhatcode** [comment] 2024-02-29 20:46
I can reproduce this on 

- Firefox on linux
- Chrome om mac

**Comment by RTechSn** [comment] 2024-03-01 10:33
@beardhatcode I apologize for bothering, but it seems that "need to reproduce" tag got added back.

**Comment by StefanKley** [comment] 2024-03-31 18:46
Problem is solved for me in 28.0.4

**Comment by bufferlow** [comment] 2024-03-31 18:54
Seems solved in 28.0.4 - work for me.

**Comment by MrRinkana** [comment] 2024-04-06 11:25
Can those who could reproduce this issue check if thats still the case after uppgrade to >28.0.3 and if not like @bufferlow's commment. If noone can reproduce it anymore maybe @RTechSn can close the issue?

Based on @beardhatcode's findings, this issue was fixed in https://github.com/nextcloud/text/commit/2c9e7a0fce22aab005b202a51b0bffcbfa47b0a8 in https://github.com/nextcloud/text/pull/5281 which was backported to [28.0.3](https://github.com/nextcloud/text/milestone/148?closed=1)

**Comment by Finn10111** [comment] 2024-04-06 21:12
> Can those who could reproduce this issue check if thats still the case after uppgrade to >28.0.3 and if not like @bufferlow's commment. If noone can reproduce it anymore maybe @RTechSn can close the issue?
> 
> Based on @beardhatcode's findings, this issue was fixed in [nextcloud/text@2c9e7a0](https://github.com/nextcloud/text/commit/2c9e7a0fce22aab005b202a51b0bffcbfa47b0a8) in [nextcloud/text#5281](https://github.com/nextcloud/text/pull/5281) which was backported to [28.0.3](https://github.com/nextcloud/text/milestone/148?closed=1)

Just upgraded to 28.0.4 and also the notes app and the issue is gone! The cursor stays at the the position where it was after switching tabs! Great, seems to be solved :+1:

**Comment by arnowelzel** [comment] 2024-04-07 11:27
> Can those who could reproduce this issue check if thats still the case after uppgrade to >28.0.3 and if not like @bufferlow's commment. If noone can reproduce it anymore maybe @RTechSn can close the issue?
> 
> Based on @beardhatcode's findings, this issue was fixed in [nextcloud/text@2c9e7a0](https://github.com/nextcloud/text/commit/2c9e7a0fce22aab005b202a51b0bffcbfa47b0a8) in [nextcloud/text#5281](https://github.com/nextcloud/text/pull/5281) which was backported to [28.0.3](https://github.com/nextcloud/text/milestone/148?closed=1)

I can confirm too, that it works now with NC 28.0.4.

**Comment by RTechSn** [comment] 2024-04-07 12:07
I can confirm too that on version 28.0.4 the issue is no longer present.

**Closed** 2024-04-07 12:07 UTC
Labels: bug, need to reproduce
