### ISSUE TITLE
Encapsulated/Managed Note Attachments

### ISSUE THREAD

**Issue by elsiehupp** [nextcloud/notes#696] opened 2021-03-14 16:43 UTC
### Is your feature request related to a problem? Please describe.
I currently use Evernote. I would like to be able to escape from Evernote. One of my main use cases for Evernote is notes with managed attachments. While Nextcloud Notes does allow for attachments, said attachments much reside at publicly accessible URLs, which makes them brittle, and also doesn't allow for using Nextcloud Notes as a place to store attachments. I would rather not have to think about where the attachments are stored.

### Describe the solution you'd like
Nextcloud Notes could allow attachments to be stored in, say, a subfolder of the Notes folder, which would be hidden in the Notes UI. Nextcloud Notes would allow attachments to be uploaded through the web interface, and it would automatically copy attachments added from elsewhere in the user's Nextcloud drive. It would also keep track of orphaned attachments and move them to a trash-collection folder to be deleted after a certain period of time.

### Describe alternatives you've considered
The main alternative is using Joplin, which manages attachments, but Joplin doesn't integrate with Nextcloud beyond using it as a WebDAV server.

### Additional context
It would be preferable for the attachment-management system to be relatively compatible with other Markdown solutions. For this reason, it may be worthwhile to copy the way Joplin manages attachments.

**Comment by stefan-niedermann** [comment] 2021-03-14 16:46
Please use the 🔍  search function before opening new issues.
Duplicate of #74

**Closed by stefan-niedermann** 2021-03-14 16:46 UTC
Labels: feature request, needs discussion

**Comment by elsiehupp** [comment] 2021-03-14 17:07
@stefan-niedermann I scanned the list, but I guess I missed that.
