### ISSUE TITLE
Ability to turn off rich text editor in the options

### ISSUE THREAD

**Issue by andreas1107** [nextcloud/notes#1293] opened 2024-05-07 06:33 UTC
**Is your feature request related to a problem? Please describe.**

I frequently get frustrated by the lower right button that pops up when I edit in plain text.

![Screenshot_20240507-083103_Nextcloud Notes_1](https://github.com/nextcloud/notes/assets/34312687/d53506e8-0156-42f4-a252-a28bbdffafa5)

**Describe the solution you'd like**

Put a toggle in Options to disable rich text, which would stop the pop-up button to the bottom right from appearing. 

**Describe alternatives you've considered**

Permanently disable the button and just have the option in the settings.

**Comment by cheywood** [comment] 2024-05-27 05:49
Likely duplicate of https://github.com/nextcloud/notes-android/issues/1819

**Comment by c-o-m-m-a-n-d-e-r-d-a-t-a** [comment] 2024-06-16 07:10
Adding comment here as well - the other request is closed despite the problem remaining... Reiterate that this is one of the most valuable apps I use, but this is infuriating...

**Comment by juliushaertl** [comment] 2024-07-12 06:02
I reopened the android notes app issue, will close this one here instead as it is not related to the server app.

**Closed by juliushaertl** 2024-07-12 06:02 UTC
Labels: needs discussion, feature request
