### ISSUE TITLE
Changing the storage location isn't applied

### ISSUE THREAD

**Issue by rmeissn** [nextcloud/notes#1235] opened 2024-02-20 07:59 UTC
I've installed Notes and wanted to use an existing folder structure for my notes. Thus, I've pointed the notes app to this folder structure (named "My_Stuff"). 
Unfortunately, this change was not applied. Whenever I've opened up the Settings menu again, it pointed to "Notes" again. 
Thus I've changed the location via the provided occ command and force-reloaded my browser -> Still pointing to "Notes".
I've changed the location in the settings menu again and changed from .md files to .txt files and back -> The new location seems to have been saved now.

## Steps to reproduce
1. Change folder location in the settings menu without touching anything else

### Expected behaviour
Changing the folder location is applied immediately.

### Actual behaviour
There are no changes applied

## Server
Please complete the following information.

- Notes app version: 4.9.2
- Nextcloud version: 28.0.2
- OS: Linux/Fedora
- PHP version: 8.2
- Database: MariaDB 10.x

## Client

- Browser (incl. version): FireFox 122
 - OS: Fedora 39

**Comment by beedaddy** [comment] 2024-02-22 11:22
I can confirm the issue, using Notes 4.9.2 and Nextcloud 27.1.6.

**Comment by joshtrichards** [comment] 2024-03-23 02:06
Duplicate of #1186

**Closed by joshtrichards** 2024-03-23 02:06 UTC
Labels: bug, need to reproduce
