### ISSUE TITLE
Checklist rendering inverted

### ISSUE THREAD

**Issue by shinenelson** [nextcloud/notes#680] opened 2021-02-07 14:06 UTC
The rendering of the checkbox button is activated in edit mode and is converted into plain text in preview mode. It should be the other way around. That is how the link tags work

## Steps to reproduce
1. Create a new note
2. Add a checklist item
3. Switch to Preview Mode

### Expected behaviour
The checkbox should be rendered in Preview mode. In Edit mode is should stay in plain text.

### Actual behaviour
The checkbox is rendered in Edit mode and plain text is shown in Preview mode

### Screenshots

Edit Mode
![image](https://user-images.githubusercontent.com/4771718/107148691-9fa13180-697a-11eb-9171-15ac6e657f03.png)

Preview Mode
![image](https://user-images.githubusercontent.com/4771718/107148710-b8114c00-697a-11eb-9c5b-5689cc8528d0.png)

## Server
Please complete the following information.

- Notes app version: 4.0.1
- Nextcloud version: 20.0.1
- OS: Debian GNU/Linux
- Web server: Apache
- PHP version: 7.3.19
- Database: MariaDB

## Client
Please complete the following information.

- Browser (incl. version): Firefox 85.0
 - OS: Debian GNU/Linux

**Comment by korelstar** [comment] 2021-02-07 14:25
Duplicate of #325

**Closed by korelstar** 2021-02-07 14:25 UTC
Labels: bug, need to reproduce
