### ISSUE TITLE
Rich Text Editor switch don't work

### ISSUE THREAD

**Issue by JordanDIG** [nextcloud/notes#983] opened 2023-03-21 14:16 UTC
Please make a clear and concise description of what the bug is. Please note, that issues with the Android app have to be reported under https://github.com/stefan-niedermann/nextcloud-notes/issues and issues with Nextcloud's Text app have to be reported under https://github.com/nextcloud/text/issues .

## Steps to reproduce
1.Create notes on an account
2.Upgrade to the latest version
3.Reopen the notes application

### Expected behaviour
Let the menu disappear.

### Actual behaviour
The menu is displayed but clicking on an option nothing happens

## Server
Please complete the following information.

- Notes app version:  lastest
- Nextcloud version: 25.0.4
- OS: Debian Docker
- Web server: Apache
- PHP version: 8.1
- Database: MariaDB

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

## Client
Please complete the following information.

- Browser (incl. version): 
 - OS: Chrome 110 Windows 11

![image](https://user-images.githubusercontent.com/38187648/226612450-79107d5d-9210-47c5-9074-3c847204b4f0.png)

## Log files
Add relevant parts of your `nextcloud.log` and/or your browser's JavaScript console here.

![image](https://user-images.githubusercontent.com/38187648/226633403-29d8061c-ca99-4b98-85fe-4c49b3989aae.png)

**Comment by provokateurin** [comment] 2023-03-21 14:52
Probably duplicate of https://github.com/nextcloud/notes/issues/982

**Comment by juliushaertl** [comment] 2023-03-21 14:59
Yes, let's close this as a duplicate of #982

**Closed as completed by juliushaertl** 2023-03-21 14:59 UTC
Labels: bug, need to reproduce
