### ISSUE TITLE
Serious rendering problem on Android 

### ISSUE THREAD

**Issue by elpraga** [nextcloud/notes#177] opened 2018-03-16 10:50 UTC
This is how are my notes rendered on my android tablet. Does anyone have a similar issue?
![screenshot_20180316-114530](https://user-images.githubusercontent.com/13814570/37516886-eff94004-290f-11e8-99c8-99bf58ece3b8.png)

**Comment by elpraga** [comment] 2018-03-27 16:28
Anyone can confirm this issue? It happens both when using Google Chrome on Android or Firefox for Android. Notes are rendered correctly when __Request desktop site__ is checked (both browsers). Google Chrome on Linux renders correctly.

**Comment by mschloesser** [comment] 2018-04-04 18:01
Hey @elpraga, I can confirm this issue on my OnePlus 3, both with Firefox and Chrome.
Are more infos needed?

**Comment by korelstar** [comment] 2018-04-14 17:18
Fixed in #187. :-)

**Closed by korelstar** 2018-04-14 17:18 UTC

**Comment by elpraga** [comment] 2018-04-15 14:35
That's great news! Thank you? Is the fix going to be pushed to the official nextcloud app page soon @korelstar ?

**Comment by korelstar** [comment] 2018-04-17 14:19
I don't have sufficient credentials for publishing a new version. This has to be done by @Henni. Unfortunately, he seems to be very busy.

But the change is very small, you could do it manually (at least for testing). See "changes" tab in the referenced PR.

**Comment by elpraga** [comment] 2018-04-21 08:12
Yes, that's what I did after all! I dared to check the patch, and when I saw how small it was, I applied it manually. Thank you!

**Comment by jancborchardt** [comment] 2018-06-05 16:54
@Henni any chance you can do a release? :) :rocket:

**Comment by jancborchardt** [comment] 2018-06-05 16:57
Also @Henni if you are too busy, of course it’s also fine to transfer maintainership – whatever is best for you. :) I’m sure that either @korelstar or @camilasan could take over maintainership (or both, if that’s possible?)

**Comment by korelstar** [comment] 2018-06-05 18:28
The only thing we need is write access to https://apps.nextcloud.com/apps/notes
I'm willing to publish a release from time to time. But I think it would be a good idea to give the rights in addition and not as replacement of @Henni.

**Comment by korelstar** [comment] 2018-06-26 08:13
Let's continue the discussion on releases under the new issue #211 :-)

**Comment by pbek** [comment] 2018-08-12 10:12
Thank you very much for the fix in version 2.4.0! It works great for me on my Huawei P10! I was almost investing my life force in writing a mobile client for https://github.com/pbek/QOwnNotes because of it. :smile:

**Comment by pbek** [comment] 2018-08-12 10:15
And I can feel your pain in releasing apps for apps.nextcloud.com... :) I had a lot of "fun" releasing new versions for Nextcloud 14 for https://github.com/pbek/qownnotesapi and https://github.com/pbek/ownbackup the last two days. :grimacing:
