### ISSUE TITLE
Horizontally scale images to text viewport

### ISSUE THREAD

**Issue by muety** [nextcloud/notes#831] opened 2022-03-15 07:48 UTC
When including large images, they overflow they page's boundaries, like this:

![image](https://user-images.githubusercontent.com/8978843/158330273-42e72296-2a38-4c21-9fd9-e82d3e1ed4ae.png)

Rather, I'd like to have them scaled down, like this:
![image](https://user-images.githubusercontent.com/8978843/158330461-e14da8f4-08b4-4465-a093-2cf285609d06.png)

All required to accomplish that should be setting `max-width: 100%` to the `img` element.

**Comment by korelstar** [comment] 2022-03-19 20:35
Thanks for your bug report! I can reproduce the issue with the current release 4.3.1. However, the next release 4.4.0 will have a new imageproxy for showing images (see #785). There, this issue does not happen. The release will take some time, but I'll close this issue for now, since there is nothing to fix anymore.

**Closed by korelstar** 2022-03-19 20:35 UTC
