### ISSUE TITLE
[FR] Put notes in groups

### ISSUE THREAD

**Issue by enoch85** [nextcloud/notes#100] opened 2017-06-11 16:02 UTC
As it is right now you type the note in one row. What I would like is to add a subject for each note instead, just like ownNotes does. The reason for this is for example if you store much information in one note you want to "categorize" or "tag" each note with a subject so that you can save much information in one note and eaisely find it.

One example is if I want to save addresses. Like it is right now, all the addresses are saved in one line, and is shown as one line in the "subject".

**Address 1 Address 2 Address 3**

Instead I would like it to be like this:

**Addresses**
*Address 1*
*Address 2*
*Address 3* 
*And so on..*

**BOLD** = The subject
*Cursive* = The actual note

This is esecially useful for the mobile app and makes it easier to find notesif you have several notes with much information in them.

**Comment by stefan-niedermann** [comment] 2017-06-14 07:03
duplicate of #8? If you put the note .txt files onto folders they are already recognized. support will be extended to support folders fully in the wwb frontend as far as i know.

**Comment by enoch85** [comment] 2017-06-14 11:07
Nope, but related. 

This is more like the pic you linked of the news app where the headlines are bold and the actual news is the note in this case. Please take a look at ownNote to see what I mean.

**Comment by korelstar** [comment] 2017-06-17 05:59
I don't get what you mean. Is this about showing the first line of the note in bold?

In your address example, I can't see, what hinders you to add line breaks in the first example. Then it's like in the second example, which is the desired variant (?)

**Comment by enoch85** [comment] 2017-07-02 11:55
OK, so I just noticed that the first line becomes the subject, what I want is groups.

**[Recipes]**
Recipe 1
Recipe 2

**[Just notes]**
Note 1
Note 2

@stefan-niedermann

**Closed** 2017-07-02 11:56 UTC
Labels: enhancement
