### ISSUE TITLE
Rich Text Editor: Copying and Pasting a Check-list  turns it into a bullet list

### ISSUE THREAD

**Issue by DamageIncorporated** [nextcloud/notes#1428] opened 2024-11-27 11:56 UTC
## Steps to reproduce
1. Open or create a ~~first~~ note, edit in rich text mode
2. Create a Check-List with several entries
3. copy the check list or a part of it to the clipboard
4. ~~open or create a second note, edit in rich text mode~~ _Update: Can be reproduced in the same note, no need to open another_
5. Paste your list ~~into the second note~~

This can be reproduced in the WebUI as well as in the Android App (if that matters).

### Expected behaviour
the check-list items should appear ~~in the second note~~ as they were copied ~~from the first note~~

### Actual behaviour
the check-list items appear as bullet-list items ~~in the second note~~

## Server
Please complete the following information.

- Notes app version: 4.11.0
- Nextcloud version: 28.0.7 Enterprise
- OS: Unknown - using a managed service from ionos.de
- Web server: Unknown - using a managed service from ionos.de 
- PHP version: Unknown - using a managed service from ionos.de
- Database: Unknown - using a managed service from ionos.de

- Browser (incl. version): Firefox 132.0.1 
 - OS: Fedora 41

**Comment by DamageIncorporated** [comment] 2024-11-29 14:28
... this also happensin the WebUI as well as in the Android App, if that matters.

**Comment by DamageIncorporated** [comment] 2024-11-29 18:30
Update: Just tried to copy and Paste Lists **in the same note** and realized the issue persists. So you don't need to open or create a new note to reproduce this. 

Updating the original issue now

**Comment by juliusknorr** [comment] 2024-12-03 13:38
- I could not reproduce this on latest main branch of text
- I can reproduce this on 28.0.10 and latest stable28 also with text only

**Comment by juliusknorr** [comment] 2024-12-03 13:40
This was fixed with Nextcloud 30, 29 in https://github.com/nextcloud/text/pull/6323.

I'll close this, but @mejo- Can you tell if a backport was not done for 28 for any specific reason?

**Closed by juliusknorr** 2024-12-03 13:40 UTC
Labels: bug, need to reproduce

**Comment by mejo-** [comment] 2024-12-03 14:08
@juliusknorr sorry, I probably forgot. Given that 28 will be EOL next week, shall I still schedule it?

**Comment by juliusknorr** [comment] 2024-12-03 14:10
No i think then it is fine as we won't have another release and the current is in freeze already

**Comment by DamageIncorporated** [comment] 2024-12-07 12:03
Thank you @juliusknorr @mejo- for looking into this...
I'll hang on until ionos updates to 30
