### ISSUE TITLE
Markdown page description - anyway to create check lists like in LML (leightweight markup language)

### ISSUE THREAD

**Issue by wgregori** [nextcloud/notes#76] opened 2017-04-01 17:54 UTC
Thanks for all the work on the notepad in Nextcloud... 
I've been using Zim-Wiki (zim-wiki.org) for some years now and find that the check box feature in the "create list" feature to be invaluable. I'd like to transition this aspect of my business to Nextcloud/notes but I cannot with out this functionality. (I see that Markdown does deal with creating a checkbox but it is not interactive.
To be clear the zim-wiki checkboxes are interactive... clicking them either checks the box or unchecks it.

Thanks again,
Wayne #

**Comment by jancborchardt** [comment] 2018-06-05 16:26
This is a duplicate of #117 (Add boxes for checking)

**Closed by jancborchardt** 2018-06-05 16:26 UTC
Labels: enhancement
