### ISSUE TITLE
add a "share preview" link

### ISSUE THREAD

**Issue by zeroepix** [nextcloud/notes#612] opened 2020-09-02 22:28 UTC
As far as I know, sharing notes is difficult. Please correct me if I'm wrong as I'd love to know how to do it easily.

As it is, it would be nice to be able to share a preview of a note from within the app itself. I would imagine a logical place for this option would be in the 3-dot menu, with something like a "share preview" link there.

Clicking this link would copy a pasteable URL onto the clipboard which you could give to someone else, and when they click that they could see a preview version of that note. Ideally the link would be permanent until revoked, and the viewer could be anonymous, if at all possible. 

There would be multiple use-cases for this sort of feature. The most obvious is to let someone else read (but not edit) a note you've written. A less obvious use-case is that it could be used for content-authoring. If you load that shared link in an iframe, you could update that content extremely easily.

**Comment by stefan-niedermann** [comment] 2020-09-03 06:07
Duplicate of https://github.com/nextcloud/notes/issues/38

**Comment by korelstar** [comment] 2020-10-01 18:51
Closing since it's a duplicate. Thanks @stefan-niedermann for pointing out

**Closed** 2020-10-01 18:51 UTC
Labels: feature request
